// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { CustomFontBatchDeleteRequestItemsItem } from "../../types/CustomFontBatchDeleteRequestItemsItem";

export const CustomFontBatchDeleteRequest: core.serialization.Schema<
    serializers.CustomFontBatchDeleteRequest.Raw,
    Webflow.CustomFontBatchDeleteRequest
> = core.serialization.object({
    items: core.serialization.list(CustomFontBatchDeleteRequestItemsItem),
});

export declare namespace CustomFontBatchDeleteRequest {
    export interface Raw {
        items: CustomFontBatchDeleteRequestItemsItem.Raw[];
    }
}
