/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { FormsListResponseFormsItemFieldsValue } from "./FormsListResponseFormsItemFieldsValue";
import { FormsListResponseFormsItemResponseSettings } from "./FormsListResponseFormsItemResponseSettings";

export const FormsListResponseFormsItem: core.serialization.ObjectSchema<
    serializers.FormsListResponseFormsItem.Raw,
    Webflow.FormsListResponseFormsItem
> = core.serialization.object({
    displayName: core.serialization.string().optional(),
    createdOn: core.serialization.date().optional(),
    lastUpdated: core.serialization.date().optional(),
    fields: core.serialization.record(core.serialization.string(), FormsListResponseFormsItemFieldsValue).optional(),
    responseSettings: FormsListResponseFormsItemResponseSettings.optional(),
    id: core.serialization.string().optional(),
    siteId: core.serialization.string().optional(),
    siteDomainId: core.serialization.string().optional(),
    pageId: core.serialization.string().optional(),
    pageName: core.serialization.string().optional(),
    formElementId: core.serialization.string().optional(),
    workspaceId: core.serialization.string().optional(),
});

export declare namespace FormsListResponseFormsItem {
    interface Raw {
        displayName?: string | null;
        createdOn?: string | null;
        lastUpdated?: string | null;
        fields?: Record<string, FormsListResponseFormsItemFieldsValue.Raw> | null;
        responseSettings?: FormsListResponseFormsItemResponseSettings.Raw | null;
        id?: string | null;
        siteId?: string | null;
        siteDomainId?: string | null;
        pageId?: string | null;
        pageName?: string | null;
        formElementId?: string | null;
        workspaceId?: string | null;
    }
}
