/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const EcommNewOrderPayloadCustomerInfo: core.serialization.ObjectSchema<
    serializers.EcommNewOrderPayloadCustomerInfo.Raw,
    Webflow.EcommNewOrderPayloadCustomerInfo
> = core.serialization.object({
    fullName: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
});

export declare namespace EcommNewOrderPayloadCustomerInfo {
    interface Raw {
        fullName?: string | null;
        email?: string | null;
    }
}
