/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const EcommOrderChangedPayloadMetadata: core.serialization.ObjectSchema<
    serializers.EcommOrderChangedPayloadMetadata.Raw,
    Webflow.EcommOrderChangedPayloadMetadata
> = core.serialization.object({
    isBuyNow: core.serialization.boolean().optional(),
});

export declare namespace EcommOrderChangedPayloadMetadata {
    interface Raw {
        isBuyNow?: boolean | null;
    }
}
