/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { OrdersGetResponseTotalsSubtotal } from "./OrdersGetResponseTotalsSubtotal";
import { OrdersGetResponseTotalsExtrasItem } from "./OrdersGetResponseTotalsExtrasItem";
import { OrdersGetResponseTotalsTotal } from "./OrdersGetResponseTotalsTotal";

export const OrdersGetResponseTotals: core.serialization.ObjectSchema<
    serializers.OrdersGetResponseTotals.Raw,
    Webflow.OrdersGetResponseTotals
> = core.serialization.object({
    subtotal: OrdersGetResponseTotalsSubtotal.optional(),
    extras: core.serialization.list(OrdersGetResponseTotalsExtrasItem).optional(),
    total: OrdersGetResponseTotalsTotal.optional(),
});

export declare namespace OrdersGetResponseTotals {
    interface Raw {
        subtotal?: OrdersGetResponseTotalsSubtotal.Raw | null;
        extras?: OrdersGetResponseTotalsExtrasItem.Raw[] | null;
        total?: OrdersGetResponseTotalsTotal.Raw | null;
    }
}
