/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const OrdersRefundResponseShippingAddressJapanType: core.serialization.Schema<
    serializers.OrdersRefundResponseShippingAddressJapanType.Raw,
    Webflow.OrdersRefundResponseShippingAddressJapanType
> = core.serialization.enum_(["kana", "kanji"]);

export declare namespace OrdersRefundResponseShippingAddressJapanType {
    type Raw = "kana" | "kanji";
}
