/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const OrdersGetResponseBillingAddressType: core.serialization.Schema<
    serializers.OrdersGetResponseBillingAddressType.Raw,
    Webflow.OrdersGetResponseBillingAddressType
> = core.serialization.enum_(["shipping", "billing"]);

export declare namespace OrdersGetResponseBillingAddressType {
    type Raw = "shipping" | "billing";
}
