/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { OrdersUpdateResponseBillingAddressType } from "./OrdersUpdateResponseBillingAddressType";
import { OrdersUpdateResponseBillingAddressJapanType } from "./OrdersUpdateResponseBillingAddressJapanType";

export const OrdersUpdateResponseBillingAddress: core.serialization.ObjectSchema<
    serializers.OrdersUpdateResponseBillingAddress.Raw,
    Webflow.OrdersUpdateResponseBillingAddress
> = core.serialization.object({
    type: OrdersUpdateResponseBillingAddressType.optional(),
    japanType: OrdersUpdateResponseBillingAddressJapanType.optional(),
    addressee: core.serialization.string().optional(),
    line1: core.serialization.string().optional(),
    line2: core.serialization.string().optional(),
    city: core.serialization.string().optional(),
    state: core.serialization.string().optional(),
    country: core.serialization.string().optional(),
    postalCode: core.serialization.string().optional(),
});

export declare namespace OrdersUpdateResponseBillingAddress {
    interface Raw {
        type?: OrdersUpdateResponseBillingAddressType.Raw | null;
        japanType?: OrdersUpdateResponseBillingAddressJapanType.Raw | null;
        addressee?: string | null;
        line1?: string | null;
        line2?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        postalCode?: string | null;
    }
}
