/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const OrdersRefundResponseBillingAddressJapanType: core.serialization.Schema<
    serializers.OrdersRefundResponseBillingAddressJapanType.Raw,
    Webflow.OrdersRefundResponseBillingAddressJapanType
> = core.serialization.enum_(["kana", "kanji"]);

export declare namespace OrdersRefundResponseBillingAddressJapanType {
    type Raw = "kana" | "kanji";
}
