/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { OrdersListResponseOrdersItemStripeCardBrand } from "./OrdersListResponseOrdersItemStripeCardBrand";
import { OrdersListResponseOrdersItemStripeCardExpires } from "./OrdersListResponseOrdersItemStripeCardExpires";

export const OrdersListResponseOrdersItemStripeCard: core.serialization.ObjectSchema<
    serializers.OrdersListResponseOrdersItemStripeCard.Raw,
    Webflow.OrdersListResponseOrdersItemStripeCard
> = core.serialization.object({
    last4: core.serialization.string().optional(),
    brand: OrdersListResponseOrdersItemStripeCardBrand.optional(),
    ownerName: core.serialization.string().optional(),
    expires: OrdersListResponseOrdersItemStripeCardExpires.optional(),
});

export declare namespace OrdersListResponseOrdersItemStripeCard {
    interface Raw {
        last4?: string | null;
        brand?: OrdersListResponseOrdersItemStripeCardBrand.Raw | null;
        ownerName?: string | null;
        expires?: OrdersListResponseOrdersItemStripeCardExpires.Raw | null;
    }
}
