/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const OrdersListResponsePagination: core.serialization.ObjectSchema<
    serializers.OrdersListResponsePagination.Raw,
    Webflow.OrdersListResponsePagination
> = core.serialization.object({
    limit: core.serialization.number().optional(),
    offset: core.serialization.number().optional(),
    total: core.serialization.number().optional(),
});

export declare namespace OrdersListResponsePagination {
    interface Raw {
        limit?: number | null;
        offset?: number | null;
        total?: number | null;
    }
}
