/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../index";

/**
 * The Asset Folders object
 */
export interface AssetsListFoldersResponse {
    /** A list of Asset folders */
    assetFolders?: Webflow.AssetsListFoldersResponseAssetFoldersItem[];
    /** Pagination object */
    pagination?: Webflow.AssetsListFoldersResponsePagination;
}
