export const CollectionsFixture = {
  collections: {
    parameters: {
      siteId: "580e63e98c9a982ac9b8b741",
    },
    response: [
      {
        _id: "580e63fc8c9a982ac9b8b745",
        lastUpdated: "2016-10-24T19:42:38.929Z",
        createdOn: "2016-10-24T19:41:48.349Z",
        name: "Blog Posts",
        slug: "post",
        singularName: "Blog Post",
      },
      {
        _id: "580e64088c9a982ac9b8b766",
        lastUpdated: "2016-10-24T19:42:00.799Z",
        createdOn: "2016-10-24T19:42:00.777Z",
        name: "Authors",
        slug: "author",
        singularName: "Author",
      },
    ],
  },
  collection: {
    parameters: {
      collectionId: "580e63fc8c9a982ac9b8b745",
    },
    response: {
      _id: "580e63fc8c9a982ac9b8b745",
      lastUpdated: "2016-10-24T19:42:38.929Z",
      createdOn: "2016-10-24T19:41:48.349Z",
      name: "Blog Posts",
      slug: "post",
      singularName: "Blog Post",
      fields: [
        {
          id: "7f62a9781291109b9e428fb47239fd35",
          editable: true,
          required: false,
          type: "RichText",
          slug: "post-body",
          name: "Post Body",
        },
        {
          validations: {
            singleLine: false,
          },
          id: "ac4ffead755a78c710c44042f528b073",
          helpText: "A summary of the blog post that appears on blog post grid",
          editable: true,
          required: false,
          type: "PlainText",
          slug: "post-summary",
          name: "Post Summary",
        },
        {
          id: "ba1cfbdaa6b38b8e95e9b5063da8a5bd",
          editable: true,
          required: false,
          type: "ImageRef",
          slug: "main-image",
          name: "Main Image",
        },
        {
          id: "a8c6ea29b08cc5b5ef966908fa1deae2",
          helpText:
            "Smaller version of main image that is used on blog post grid",
          editable: true,
          required: false,
          type: "ImageRef",
          slug: "thumbnail-image",
          name: "Thumbnail image",
        },
        {
          id: "87e79a644a6fb5729940ec24e0012f01",
          editable: true,
          required: false,
          type: "Set",
          innerType: "ImageRef",
          slug: "picture-gallery",
          name: "Picture Gallery",
        },
        {
          id: "1e54974d97181032d3206ea021668e5f",
          editable: true,
          required: false,
          type: "Bool",
          slug: "featured",
          name: "Featured?",
        },
        {
          id: "648463cbc042ab079c2b99430a398ae5",
          editable: true,
          required: false,
          type: "Color",
          slug: "color",
          name: "Color",
        },
        {
          validations: {
            collectionId: "580e64088c9a982ac9b8b766",
          },
          id: "ea9067c48edee510de71fe503fa2fb51",
          editable: true,
          required: false,
          type: "ItemRef",
          slug: "author",
          name: "Author",
        },
        {
          validations: {
            maxLength: 256,
          },
          id: "60c0667e27b6d5a6daedec3a641265f6",
          editable: true,
          required: true,
          type: "PlainText",
          slug: "name",
          name: "Name",
        },
        {
          validations: {
            messages: {
              maxLength: "Must be less than 256 characters",
              pattern:
                "Must be alphanumerical and not contain any spaces or special characters",
            },
            pattern: {},
            maxLength: 256,
          },
          id: "8f0c953df91d10b767d66e1d7d00d631",
          unique: true,
          editable: true,
          required: true,
          type: "PlainText",
          slug: "slug",
          name: "Slug",
        },
        {
          default: false,
          id: "e4e92e700d70faffac6fa82ff2bfaece",
          editable: true,
          required: true,
          type: "Bool",
          slug: "_archived",
          name: "Archived",
        },
        {
          default: false,
          id: "f2675b2ac4fcef746b24d4a320887ef8",
          editable: true,
          required: true,
          type: "Bool",
          slug: "_draft",
          name: "Draft",
        },
        {
          id: "0913a35d92208bdf8fbf3ed1e39b771e",
          editable: false,
          required: false,
          type: "Date",
          slug: "created-on",
          name: "Created On",
        },
        {
          id: "3de04889465fe6d718e47b152ef5bb4d",
          editable: false,
          required: false,
          type: "Date",
          slug: "updated-on",
          name: "Updated On",
        },
        {
          id: "2a3cd866d5dbb294896130b233218626",
          editable: false,
          required: false,
          type: "Date",
          slug: "published-on",
          name: "Published On",
        },
        {
          id: "62c18561b9e89517751c6d8712d48f91",
          editable: false,
          required: false,
          type: "User",
          slug: "created-by",
          name: "Created By",
        },
        {
          id: "50918093b4e4d4eca1e83c25bcdc06a4",
          editable: false,
          required: false,
          type: "User",
          slug: "updated-by",
          name: "Updated By",
        },
        {
          id: "5c4587f18b32ef245daeaadfcba7860b",
          editable: false,
          required: false,
          type: "User",
          slug: "published-by",
          name: "Published By",
        },
        {
          id: "7f62a9781291109b9e428fb47239fd35",
          editable: true,
          required: false,
          type: "RichText",
          slug: "post-body",
          name: "Post Body",
        },
        {
          validations: {
            singleLine: false,
          },
          id: "ac4ffead755a78c710c44042f528b073",
          helpText: "A summary of the blog post that appears on blog post grid",
          editable: true,
          required: false,
          type: "PlainText",
          slug: "post-summary",
          name: "Post Summary",
        },
        {
          id: "ba1cfbdaa6b38b8e95e9b5063da8a5bd",
          editable: true,
          required: false,
          type: "ImageRef",
          slug: "main-image",
          name: "Main Image",
        },
        {
          id: "a8c6ea29b08cc5b5ef966908fa1deae2",
          helpText:
            "Smaller version of main image that is used on blog post grid",
          editable: true,
          required: false,
          type: "ImageRef",
          slug: "thumbnail-image",
          name: "Thumbnail image",
        },
        {
          id: "87e79a644a6fb5729940ec24e0012f01",
          editable: true,
          required: false,
          type: "Set",
          innerType: "ImageRef",
          slug: "picture-gallery",
          name: "Picture Gallery",
        },
        {
          id: "1e54974d97181032d3206ea021668e5f",
          editable: true,
          required: false,
          type: "Bool",
          slug: "featured",
          name: "Featured?",
        },
        {
          id: "648463cbc042ab079c2b99430a398ae5",
          editable: true,
          required: false,
          type: "Color",
          slug: "color",
          name: "Color",
        },
        {
          validations: {
            collectionId: "580e64088c9a982ac9b8b766",
          },
          id: "ea9067c48edee510de71fe503fa2fb51",
          editable: true,
          required: false,
          type: "ItemRef",
          slug: "author",
          name: "Author",
        },
        {
          validations: {
            maxLength: 256,
          },
          id: "60c0667e27b6d5a6daedec3a641265f6",
          editable: true,
          required: true,
          type: "PlainText",
          slug: "name",
          name: "Name",
        },
        {
          validations: {
            messages: {
              maxLength: "Must be less than 256 characters",
              pattern:
                "Must be alphanumerical and not contain any spaces or special characters",
            },
            pattern: {},
            maxLength: 256,
          },
          id: "8f0c953df91d10b767d66e1d7d00d631",
          unique: true,
          editable: true,
          required: true,
          type: "PlainText",
          slug: "slug",
          name: "Slug",
        },
        {
          default: false,
          id: "e4e92e700d70faffac6fa82ff2bfaece",
          editable: true,
          required: true,
          type: "Bool",
          slug: "_archived",
          name: "Archived",
        },
        {
          default: false,
          id: "f2675b2ac4fcef746b24d4a320887ef8",
          editable: true,
          required: true,
          type: "Bool",
          slug: "_draft",
          name: "Draft",
        },
        {
          id: "0913a35d92208bdf8fbf3ed1e39b771e",
          editable: false,
          required: false,
          type: "Date",
          slug: "created-on",
          name: "Created On",
        },
        {
          id: "3de04889465fe6d718e47b152ef5bb4d",
          editable: false,
          required: false,
          type: "Date",
          slug: "updated-on",
          name: "Updated On",
        },
        {
          id: "2a3cd866d5dbb294896130b233218626",
          editable: false,
          required: false,
          type: "Date",
          slug: "published-on",
          name: "Published On",
        },
        {
          id: "62c18561b9e89517751c6d8712d48f91",
          editable: false,
          required: false,
          type: "User",
          slug: "created-by",
          name: "Created By",
        },
        {
          id: "50918093b4e4d4eca1e83c25bcdc06a4",
          editable: false,
          required: false,
          type: "User",
          slug: "updated-by",
          name: "Updated By",
        },
        {
          id: "5c4587f18b32ef245daeaadfcba7860b",
          editable: false,
          required: false,
          type: "User",
          slug: "published-by",
          name: "Published By",
        },
      ],
    },
  },
};

export default CollectionsFixture;
