/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Webflow from "../../../../../api";
import * as core from "../../../../../core";

export const FormsUpdateSubmissionRequest: core.serialization.Schema<
    serializers.FormsUpdateSubmissionRequest.Raw,
    Webflow.FormsUpdateSubmissionRequest
> = core.serialization.object({
    formSubmissionData: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace FormsUpdateSubmissionRequest {
    interface Raw {
        formSubmissionData?: Record<string, unknown> | null;
    }
}
