/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";

export const AssetsUpdateRequest: core.serialization.Schema<
    serializers.AssetsUpdateRequest.Raw,
    Webflow.AssetsUpdateRequest
> = core.serialization.object({
    localeId: core.serialization.string().optional(),
    displayName: core.serialization.string().optional(),
});

export declare namespace AssetsUpdateRequest {
    interface Raw {
        localeId?: string | null;
        displayName?: string | null;
    }
}
