// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const AssetsUpdateRequest: core.serialization.Schema<
    serializers.AssetsUpdateRequest.Raw,
    Omit<Webflow.AssetsUpdateRequest, "localeId">
> = core.serialization.object({
    displayName: core.serialization.string().optional(),
    altText: core.serialization.string().optional(),
});

export declare namespace AssetsUpdateRequest {
    export interface Raw {
        displayName?: string | null;
        altText?: string | null;
    }
}
