/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../index";

/**
 * @example
 *     {
 *         skus: [{
 *                 fieldData: {
 *                     name: "Colorful T-shirt - Default",
 *                     slug: "colorful-t-shirt-default",
 *                     price: {
 *                         value: 2499,
 *                         unit: "USD",
 *                         currency: "USD"
 *                     }
 *                 }
 *             }]
 *     }
 */
export interface ProductsCreateSkuRequest {
    publishStatus?: Webflow.PublishStatus;
    /** An array of the SKU data your are adding */
    skus: Webflow.Sku[];
}
