/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../index";

/**
 * @example
 *     {
 *         sku: {
 *             id: "66072fb71b89448912e2681c",
 *             cmsLocaleId: "653ad57de882f528b32e810e",
 *             lastPublished: new Date("2023-03-17T18:47:35.000Z"),
 *             lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
 *             createdOn: new Date("2023-03-17T18:47:35.000Z"),
 *             fieldData: {
 *                 name: "Colorful T-shirt - Default",
 *                 slug: "colorful-t-shirt-default",
 *                 price: {
 *                     value: 2499,
 *                     unit: "USD",
 *                     currency: "USD"
 *                 }
 *             }
 *         }
 *     }
 */
export interface ProductsUpdateSkuRequest {
    publishStatus?: Webflow.PublishStatus;
    sku: Webflow.Sku;
}
