/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const AccessGroupsListRequestSort: core.serialization.Schema<
    serializers.AccessGroupsListRequestSort.Raw,
    Webflow.AccessGroupsListRequestSort
> = core.serialization.enum_(["CreatedOn", "-CreatedOn"]);

export declare namespace AccessGroupsListRequestSort {
    type Raw = "CreatedOn" | "-CreatedOn";
}
