/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The content type of the file. Defaults to application/json
 */
export type WellKnownFileContentType = "application/json" | "text/plain";

export const WellKnownFileContentType = {
    ApplicationJson: "application/json",
    TextPlain: "text/plain",
} as const;
