/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../index";

/**
 * The availabile inventory for an item
 */
export interface EcommInventoryChangedPayload {
    /** Unique identifier for a SKU item */
    id?: string;
    /** Total quantity of items remaining in inventory (if inventoryType is finite) */
    quantity?: number;
    /** infinite or finite */
    inventoryType?: Webflow.EcommInventoryChangedPayloadInventoryType;
}
