/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../../index";

/**
 * @example
 *     {
 *         id: "42b720ef280c7a7a3be8cabe",
 *         cmsLocaleId: "653ad57de882f528b32e810e",
 *         lastPublished: "2022-11-29T16:22:43.159Z",
 *         lastUpdated: "2022-11-17T17:19:43.282Z",
 *         createdOn: "2022-11-17T17:11:57.148Z",
 *         isArchived: false,
 *         isDraft: false,
 *         fieldData: {
 *             name: "Pan Galactic Gargle Blaster Recipe",
 *             slug: "pan-galactic-gargle-blaster"
 *         }
 *     }
 */
export interface ItemsUpdateItemRequest {
    /** Unique identifier for the Item */
    id: string;
    /** Identifier for the locale of the CMS item */
    cmsLocaleId?: string;
    /** The date the item was last published */
    lastPublished?: string;
    /** The date the item was last updated */
    lastUpdated?: string;
    /** The date the item was created */
    createdOn?: string;
    /** Boolean determining if the Item is set to archived */
    isArchived?: boolean;
    /** Boolean determining if the Item is set to draft */
    isDraft?: boolean;
    fieldData?: Webflow.collections.ItemsUpdateItemRequestFieldData;
}
