/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         itemIds: []
 *     }
 */
export interface ItemsPublishItemRequest {
    itemIds: string[];
}
