/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../../index";

/**
 * @example
 *     {}
 */
export interface ItemsDeleteItemsLiveRequest {
    items?: Webflow.collections.ItemsDeleteItemsLiveRequestItemsItem[];
}
