// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient";
import { AuditLogs } from "../resources/auditLogs/client/Client";

export declare namespace Workspaces {
    export interface Options extends BaseClientOptions {}
}

export class Workspaces {
    protected readonly _options: Workspaces.Options;
    protected _auditLogs: AuditLogs | undefined;

    constructor(_options: Workspaces.Options = {}) {
        this._options = _options;
    }

    public get auditLogs(): AuditLogs {
        return (this._auditLogs ??= new AuditLogs(this._options));
    }
}
