/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Webflow from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItemLocation } from "./ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItemLocation";

export const ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItem: core.serialization.ObjectSchema<
    serializers.sites.ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItem.Raw,
    Webflow.sites.ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItem
> = core.serialization.object({
    id: core.serialization.string(),
    location: ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItemLocation,
    version: core.serialization.string(),
    attributes: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItem {
    interface Raw {
        id: string;
        location: ScriptsListCustomCodeBlocksResponseBlocksItemScriptsItemLocation.Raw;
        version: string;
        attributes?: Record<string, unknown> | null;
    }
}
