// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         localeId: "65427cf400e02b306eaa04a0",
 *         limit: 1.1,
 *         offset: 1.1
 *     }
 */
export interface PagesGetContentRequest {
    /**
     * Unique identifier for a specific Locale.
     *
     * [Lear more about localization.](/data/v2.0.0/docs/working-with-localization)
     */
    localeId?: string;
    /** Maximum number of records to be returned (max limit: 100) */
    limit?: number;
    /** Offset used for pagination if the results have more than limit records */
    offset?: number;
}
