// This file was auto-generated by Fern from our API Definition.

/**
 * Valid IANA time zone used to align time bucket boundaries. Use canonical names such as `UTC` or `America/New_York`. Bucket timestamps are returned as UTC instants for local bucket starts in this time zone; for example, `America/New_York` local midnight on April 1, 2026 is returned as `2026-04-01T04:00:00.000Z`.
 */
export type AnalyzeBucketTimeZone = string;
