// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

/**
 * The Webhook payload for when a branch is explicitly deleted
 */
export interface BranchDeletedWebhook {
    triggerType?: string;
    payload?: Webflow.BranchDeletedWebhookPayload;
}
