// This file was auto-generated by Fern from our API Definition.

export interface BranchCreatedWebhookPayload {
    siteId?: string;
    branchId?: string;
    /** ID of the branch page (the duplicate page). */
    pageId?: string;
    /** ID of the original page branched from, or an empty string for standalone branches. */
    parentPageId?: string;
    pageName?: string;
    createdBy?: string;
    createdOn?: Date;
}
