/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * The Webhook payload for when a Collection Item is changed
 */
export interface CollectionItemChanged {
    /** The type of event that triggered the request */
    triggerType: "collection_item_changed";
    payload: Webflow.CollectionItemChangedPayload;
}
