/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * Represents a property of a component instance in the DOM. A property contains a list of both the raw text and the HTML representation, allowing for flexibility in rendering and processing. Additional attributes can be associated with the text for styling or other purposes.
 */
export interface ComponentProperty {
    /** The ID of the property. */
    propertyId?: string;
    type?: Webflow.ComponentPropertyType;
    label?: string;
    text?: Webflow.TextNode;
}
