// This file was auto-generated by Fern from our API Definition.

export const CustomRoleAuditLogItemEventSubType = {
    RoleCreated: "role_created",
    RoleUpdated: "role_updated",
    RoleDeleted: "role_deleted",
} as const;
export type CustomRoleAuditLogItemEventSubType =
    (typeof CustomRoleAuditLogItemEventSubType)[keyof typeof CustomRoleAuditLogItemEventSubType];
