// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

/**
 * Presigned S3 upload details. Post the font binary to `url` as `multipart/form-data`, including every key from `fields` plus the binary itself in a field named `file`. The `file` field must be the last field in the form.
 */
export interface CustomFontUpload {
    /** The S3 endpoint to POST the font binary to */
    url: string;
    fields: Webflow.CustomFontUploadFields;
    /** ISO 8601 timestamp after which the presigned URL expires (approximately 15 minutes from issuance) */
    expiresAt: Date;
}
