/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Registered custom code for application
 */
export interface CustomCodeResponse {
    /** Human readable id, derived from the user-specified display name */
    id?: string;
    /** Timestamp when the script version was created */
    createdOn?: string;
    /** Timestamp when the script version was last updated */
    lastUpdated?: string;
    /** URI for an externally hosted script location */
    hostedLocation?: string;
    /** Sub-Resource Integrity Hash. Only required for externally hosted scripts (passed via hostedLocation) */
    integrityHash?: string;
    /** Define whether the script can be copied on site duplication and transfer */
    canCopy?: boolean;
    /** A Semantic Version (SemVer) string, denoting the version of the script */
    version?: string;
    /** User-facing name for the script */
    displayName?: string;
}
