// This file was auto-generated by Fern from our API Definition.

/**
 * A variable font axis definition
 */
export interface CustomFontAxis {
    /** The four-character OpenType axis tag, consisting of exactly 4 printable ASCII characters (for example, `wght`, `opsz`, `slnt`, `wdth`) */
    tag: string;
    /** Optional human-readable label for the axis */
    name?: string;
    /** Minimum value for the axis */
    min: number;
    /** Maximum value for the axis */
    max: number;
    /** Default value for the axis. Must be between `min` and `max` (inclusive). Violating this constraint returns `400 BadArgument` with an error prefixed `fontMetadata.axes`. */
    defaultValue: number;
}
