// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

/**
 * Per-item result of a bulk-delete operation
 */
export interface CustomFontBatchDeleteResponse {
    deleted: Webflow.CustomFontBatchDeleteResponseDeletedItem[];
    failed: Webflow.CustomFontBatchDeleteResponseFailedItem[];
}
