/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Choose these appropriate field type for your collection data
 */
export type FieldType =
    | "Color"
    | "DateTime"
    | "Email"
    | "ExtFileRef"
    | "File"
    | "Image"
    | "Link"
    | "MultiImage"
    | "MultiReference"
    | "Number"
    | "Option"
    | "Phone"
    | "PlainText"
    | "Reference"
    | "RichText"
    | "Switch"
    | "VideoLink";

export const FieldType = {
    Color: "Color",
    DateTime: "DateTime",
    Email: "Email",
    ExtFileRef: "ExtFileRef",
    File: "File",
    Image: "Image",
    Link: "Link",
    MultiImage: "MultiImage",
    MultiReference: "MultiReference",
    Number: "Number",
    Option: "Option",
    Phone: "Phone",
    PlainText: "PlainText",
    Reference: "Reference",
    RichText: "RichText",
    Switch: "Switch",
    VideoLink: "VideoLink",
} as const;
