/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * Details about the field of a collection
 */
export type FieldCreate =
    /**
     * A field that returns static data from the CMS. See the [documentation for a list of field types](/data/reference/field-types-item-values). */
    | Webflow.StaticField
    /**
     * A field that references item(s) in another collection. */
    | Webflow.ReferenceField;
