/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * The validations for the field
 */
export interface FieldValidations {
    additionalProperties?: Webflow.FieldValidationsAdditionalProperties;
}
