// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

/**
 * A Webflow form
 */
export interface Form {
    /** The Form name displayed on the site */
    displayName?: string;
    /** Date that the Form was created on */
    createdOn?: Date;
    /** Date that the Form was last updated on */
    lastUpdated?: Date;
    /** A collection of form field objects */
    fields?: Webflow.FormField;
    /** Settings for form responses */
    responseSettings?: Webflow.FormResponseSettings;
    /** The unique ID for the Form */
    id?: string;
    /** The unique ID of the Site the Form belongs to */
    siteId?: string;
    /** The unique ID corresponding to the site's Domain name */
    siteDomainId?: string;
    /** The unique ID for the Page on which the Form is placed */
    pageId?: string;
    /** The user-visible name of the Page where the Form is placed */
    pageName?: string;
    /** The unique ID of the Form element */
    formElementId?: string;
    /** The unique ID of the Workspace the Site belongs to */
    workspaceId?: string;
}
