/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents an image within the DOM. It contains details about the image, such as its alternative text (alt) for accessibility and an asset identifier for fetching the actual image resource. Additional attributes can be associated with the image for styling or other purposes.
 */
export interface ImageNode {
    alt?: string;
    assetId?: string;
}
