// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

/**
 * A Collection Item returned by `items/insert`. Locale variants of the same item share an `id` and differ by `cmsLocaleId`. An entry that selects several locales with `cmsLocaleIds` or `allCmsLocales` returns one item per locale, so match a returned item to the entry that created it on `id` and `cmsLocaleId` rather than on position.
 */
export interface InsertedCollectionItem {
    /** Unique identifier for the Item */
    id?: string;
    /** Identifier for the locale of the CMS item */
    cmsLocaleId?: string;
    /** The date the item was last published. `null` for the staged items this endpoint creates. */
    lastPublished?: string;
    /** The date the item was last updated */
    lastUpdated?: string;
    /** The date the item was created */
    createdOn?: string;
    /** Boolean determining if the Item is set to archived */
    isArchived?: boolean;
    /** Whether the item is in a draft state. `true` unless the request set `isDraft: false`. */
    isDraft?: boolean;
    fieldData: Webflow.InsertedCollectionItemFieldData;
}
