// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

export interface InviteWorkspaceMemberRequestBodyEmailSiteAccessItem {
    siteId: string;
    siteRole: Webflow.InviteWorkspaceMemberRequestBodyEmailSiteAccessItemSiteRole;
    /** ID of the custom Site Role named by `siteRole`. Requires `siteRole` to be `custom`, and rejected with any other `siteRole`. Rejected if the id doesn't name a client-eligible custom Site Role belonging to this workspace. */
    siteRoleId?: string;
}
