/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "..";

export interface Locales {
    /** The primary locale for the site or application. */
    primary?: Webflow.Locale;
    /** A list of secondary locales available for the site or application. */
    secondary?: Webflow.Locale[];
}
