/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

/**
 * A generic representation of a content element within the Document Object Model (DOM). Each node has a unique identifier and a specific type that determines its content structure and attributes.
 */
export type Node =
    | Webflow.Node.Text
    | Webflow.Node.Image
    | Webflow.Node.ComponentInstance
    | Webflow.Node.TextInput
    | Webflow.Node.Select
    | Webflow.Node.SubmitButton
    | Webflow.Node.SearchButton;

export declare namespace Node {
    interface Text extends Webflow.TextNodeDom {
        type: "text";
    }

    interface Image extends Webflow.ImageNodeDom {
        type: "image";
    }

    interface ComponentInstance extends Webflow.ComponentNodeDom {
        type: "component-instance";
    }

    interface TextInput extends Webflow.TextInputNodeDom {
        type: "text-input";
    }

    interface Select extends Webflow.SelectNodeDom {
        type: "select";
    }

    interface SubmitButton extends Webflow.SubmitButtonNodeDom {
        type: "submit-button";
    }

    interface SearchButton extends Webflow.SearchButtonNodeDom {
        type: "search-button";
    }
}
