/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

export interface NotEnterprisePlanSite {
    /** Error code */
    code?: "missing_scopes";
    /** Error message */
    message?: string;
    /** Link to more information */
    externalReference?: string;
    /** Array of errors */
    details?: Webflow.ErrorDetailsItem[];
}
