/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "..";

/**
 * Results from order list
 */
export interface OrderList {
    /** List of orders */
    items?: Webflow.Order[];
    pagination?: Webflow.Pagination;
}
