/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "..";

/**
 * The Product object
 */
export interface Product {
    /** Unique identifier for the Product */
    id?: string;
    /** Identifier for the locale of the CMS item */
    cmsLocaleId?: string;
    /** The date the Product was last published */
    lastPublished?: Date;
    /** The date the Product was last updated */
    lastUpdated?: Date;
    /** The date the Product was created */
    createdOn?: Date;
    /** Boolean determining if the Product is set to archived */
    isArchived?: boolean;
    /** Boolean determining if the Product is set to draft */
    isDraft?: boolean;
    fieldData?: Webflow.ProductFieldData;
}
