// This file was auto-generated by Fern from our API Definition.

/** Indicate whether your Product should be set as "staging" or "live" */
export const PublishStatus = {
    Staging: "staging",
    Live: "live",
} as const;
export type PublishStatus = (typeof PublishStatus)[keyof typeof PublishStatus];
