/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents search button elements within the DOM. It contains the text of the button. Additional attributes can be associated with the text for styling or other purposes.
 */
export interface SearchButtonNodeDom {
    /** Node UUID */
    id?: string;
    /** The text content of the search button. */
    value: string;
    /** The custom attributes of the node */
    attributes?: Record<string, string>;
}
