/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * comparison price of SKU
 */
export interface SkuFieldDataCompareAtPrice {
    /** Price of SKU */
    value?: number;
    /** Currency of Item */
    unit?: string;
}
