// This file was auto-generated by Fern from our API Definition.

/** The status of the plan */
export const SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus = {
    Active: "active",
    Inactive: "inactive",
    Canceled: "canceled",
} as const;
export type SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus =
    (typeof SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus)[keyof typeof SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus];
