/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enumerated Product variants/Options for the SKU
 */
export interface SkuPropertyListEnumItem {
    /** Unique identifier for a Product variant/Option */
    id: string;
    /** Name of the Product variant/Option */
    name: string;
    /** Slug for the Product variant/Option in the Site URL structure */
    slug: string;
}
