/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Choose these appropriate field type for your collection data
 */
export type StaticFieldType =
    | "Color"
    | "DateTime"
    | "Email"
    | "File"
    | "Image"
    | "Link"
    | "MultiImage"
    | "Number"
    | "Phone"
    | "PlainText"
    | "RichText"
    | "Switch"
    | "Video";

export const StaticFieldType = {
    Color: "Color",
    DateTime: "DateTime",
    Email: "Email",
    File: "File",
    Image: "Image",
    Link: "Link",
    MultiImage: "MultiImage",
    Number: "Number",
    Phone: "Phone",
    PlainText: "PlainText",
    RichText: "RichText",
    Switch: "Switch",
    Video: "Video",
} as const;
