// This file was auto-generated by Fern from our API Definition.

/**
 * Represents submit button elements within the DOM. It contains the text and waiting text of the button. Additional attributes can be associated with the text for styling or other purposes.
 */
export interface SubmitButtonNode {
    /** Node UUID */
    id: string;
    /** The text content of the submit button. */
    value: string;
    /** The text to show while the form is submitting. */
    waitingText: string;
    /** The custom attributes of the node */
    attributes?: Record<string, string>;
}
