// This file was auto-generated by Fern from our API Definition.

/** Bucket size for a time on page timeseries. `day` returns one value per day and `week` returns one value per week. */
export const TimeOnPageGranularityPeriod = {
    Day: "day",
    Week: "week",
} as const;
export type TimeOnPageGranularityPeriod =
    (typeof TimeOnPageGranularityPeriod)[keyof typeof TimeOnPageGranularityPeriod];
