// This file was auto-generated by Fern from our API Definition.

/**
 * The unit each `averageSeconds` value is averaged over.
 * - `session`: average time on page per session.
 * - `user`: average time on page per unique user.
 * - `pageview`: average time on page per pageview.
 */
export const TimeOnPageMetricScope = {
    Session: "session",
    User: "user",
    Pageview: "pageview",
} as const;
export type TimeOnPageMetricScope = (typeof TimeOnPageMetricScope)[keyof typeof TimeOnPageMetricScope];
