// This file was auto-generated by Fern from our API Definition.

/**
 * The unit each `count` data point is measured in.
 * - `session`: number of sessions.
 * - `user`: number of unique users.
 * - `pageview`: number of page views.
 */
export const TrafficMetricScope = {
    Session: "session",
    User: "user",
    Pageview: "pageview",
} as const;
export type TrafficMetricScope = (typeof TrafficMetricScope)[keyof typeof TrafficMetricScope];
