// This file was auto-generated by Fern from our API Definition.

export const UserAccessAuditLogItemEventSubType = {
    Login: "login",
    Logout: "logout",
} as const;
export type UserAccessAuditLogItemEventSubType =
    (typeof UserAccessAuditLogItemEventSubType)[keyof typeof UserAccessAuditLogItemEventSubType];
