/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

export interface WebhookList {
    webhooks?: Webflow.Webhook[];
    pagination?: Webflow.Pagination;
}
