/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../index";

export interface WorkspaceMembership {
    targetUser?: Webflow.WorkspaceAuditLogItemPayloadWorkspaceMembershipTargetUser;
    method?: Webflow.WorkspaceAuditLogItemPayloadWorkspaceMembershipMethod;
    userType?: Webflow.WorkspaceAuditLogItemPayloadWorkspaceMembershipUserType;
    /** The name of the role that was assigned to the user */
    roleName?: string;
    /** The previous role that the user had */
    previousRoleName?: string;
}
