/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WorkspaceAuditLogItemPayloadUserAccessMethod = "dashboard" | "sso" | "api" | "google";

export const WorkspaceAuditLogItemPayloadUserAccessMethod = {
    Dashboard: "dashboard",
    Sso: "sso",
    Api: "api",
    Google: "google",
} as const;
