// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../index";

export interface WorkspaceInvitationAuditLogItem {
    eventSubType?: Webflow.WorkspaceInvitationAuditLogItemEventSubType;
    payload?: Webflow.WorkspaceInvitation;
}
