// This file was auto-generated by Fern from our API Definition.

export const WorkspaceAuditLogItemPayloadSiteMembershipUserType = {
    Member: "member",
    Guest: "guest",
    Reviewer: "reviewer",
    Client: "client",
} as const;
export type WorkspaceAuditLogItemPayloadSiteMembershipUserType =
    (typeof WorkspaceAuditLogItemPayloadSiteMembershipUserType)[keyof typeof WorkspaceAuditLogItemPayloadSiteMembershipUserType];
