// This file was auto-generated by Fern from our API Definition.

/** Whether the update was applied */
export const WorkspaceBulkRoleChangeResponseResultsItemOutcome = {
    Updated: "updated",
    Failed: "failed",
} as const;
export type WorkspaceBulkRoleChangeResponseResultsItemOutcome =
    (typeof WorkspaceBulkRoleChangeResponseResultsItemOutcome)[keyof typeof WorkspaceBulkRoleChangeResponseResultsItemOutcome];
