/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";
import { FieldCreate } from "../../../../types/FieldCreate";

export const CollectionsCreateRequest: core.serialization.Schema<
    serializers.CollectionsCreateRequest.Raw,
    Webflow.CollectionsCreateRequest
> = core.serialization.object({
    displayName: core.serialization.string(),
    singularName: core.serialization.string(),
    slug: core.serialization.string().optional(),
    fields: core.serialization.list(FieldCreate).optional(),
});

export declare namespace CollectionsCreateRequest {
    export interface Raw {
        displayName: string;
        singularName: string;
        slug?: string | null;
        fields?: FieldCreate.Raw[] | null;
    }
}
