/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const DomWriteNodesItem: core.serialization.ObjectSchema<
    serializers.DomWriteNodesItem.Raw,
    Webflow.DomWriteNodesItem
> = core.serialization.object({
    nodeId: core.serialization.string(),
    text: core.serialization.string(),
});

export declare namespace DomWriteNodesItem {
    interface Raw {
        nodeId: string;
        text: string;
    }
}
