/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const UpdatePageSettingsRequestOpenGraph: core.serialization.ObjectSchema<
    serializers.UpdatePageSettingsRequestOpenGraph.Raw,
    Webflow.UpdatePageSettingsRequestOpenGraph
> = core.serialization.object({
    title: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace UpdatePageSettingsRequestOpenGraph {
    interface Raw {
        title?: string | null;
        description?: string | null;
    }
}
