/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { CollectionItemUnpublishedPayloadPayload } from "./CollectionItemUnpublishedPayloadPayload";

export const CollectionItemUnpublishedPayload: core.serialization.ObjectSchema<
    serializers.CollectionItemUnpublishedPayload.Raw,
    Webflow.CollectionItemUnpublishedPayload
> = core.serialization.object({
    triggerType: core.serialization.string().optional(),
    payload: CollectionItemUnpublishedPayloadPayload.optional(),
});

export declare namespace CollectionItemUnpublishedPayload {
    interface Raw {
        triggerType?: string | null;
        payload?: CollectionItemUnpublishedPayloadPayload.Raw | null;
    }
}
