/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const InventoryUpdateResponseInventoryType: core.serialization.Schema<
    serializers.InventoryUpdateResponseInventoryType.Raw,
    Webflow.InventoryUpdateResponseInventoryType
> = core.serialization.enum_(["infinite", "finite"]);

export declare namespace InventoryUpdateResponseInventoryType {
    type Raw = "infinite" | "finite";
}
