/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../index";

export interface ItemsCreateItemLiveRequestItems {
    /** List of collection items to create */
    items?: Webflow.CollectionItem[];
}
