// This file was auto-generated by Fern from our API Definition.

export const ItemsListItemsLiveRequestSortBy = {
    CreatedOn: "createdOn",
    LastPublished: "lastPublished",
    LastUpdated: "lastUpdated",
    Name: "name",
    Slug: "slug",
} as const;
export type ItemsListItemsLiveRequestSortBy =
    (typeof ItemsListItemsLiveRequestSortBy)[keyof typeof ItemsListItemsLiveRequestSortBy];
