// This file was auto-generated by Fern from our API Definition.

export const ItemsListItemsRequestSortBy = {
    LastPublished: "lastPublished",
    Name: "name",
    Slug: "slug",
} as const;
export type ItemsListItemsRequestSortBy =
    (typeof ItemsListItemsRequestSortBy)[keyof typeof ItemsListItemsRequestSortBy];
