/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../index";

export type ItemsCreateItemRequest = Webflow.CollectionItemPostSingle | Webflow.collections.MultipleItems;
