/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../index";

export interface MultipleItems {
    /** An array of items to create */
    items?: Webflow.CollectionItemPostSingle[];
}
