/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateStaticContentRequestNodesItem } from "../../types/UpdateStaticContentRequestNodesItem";

export const UpdateStaticContentRequest: core.serialization.Schema<
    serializers.UpdateStaticContentRequest.Raw,
    Omit<Webflow.UpdateStaticContentRequest, "localeId">
> = core.serialization.object({
    nodes: core.serialization.list(UpdateStaticContentRequestNodesItem),
});

export declare namespace UpdateStaticContentRequest {
    interface Raw {
        nodes: UpdateStaticContentRequestNodesItem.Raw[];
    }
}
