/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface OrdersUpdateRequest {
    /** Arbitrary data for your records */
    comment?: string;
    /** Company or method used to ship order */
    shippingProvider?: string;
    /** Tracking number for order shipment */
    shippingTracking?: string;
    /** URL to track order shipment */
    shippingTrackingUrl?: string;
}
