/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the plan
 */
export type ProductsCreateSkuResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus =
    | "active"
    | "inactive"
    | "canceled";

export const ProductsCreateSkuResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus = {
    Active: "active",
    Inactive: "inactive",
    Canceled: "canceled",
} as const;
