/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../index";

export interface ProductsCreateSkuResponseSkusItemFieldDataEcSkuSubscriptionPlan {
    /** Interval of subscription renewal */
    interval?: Webflow.ProductsCreateSkuResponseSkusItemFieldDataEcSkuSubscriptionPlanInterval;
    /** Frequncy of billing within interval */
    frequency?: number;
    /** Number of days of a trial */
    trial?: number;
    plans?: Webflow.ProductsCreateSkuResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItem[];
}
