/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Interval of subscription renewal
 */
export type ProductsUpdateSkuResponseFieldDataEcSkuSubscriptionPlanInterval = "day" | "week" | "month" | "year";

export const ProductsUpdateSkuResponseFieldDataEcSkuSubscriptionPlanInterval = {
    Day: "day",
    Week: "week",
    Month: "month",
    Year: "year",
} as const;
