/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Webflow from "../../api";
import * as core from "../../core";

export const Authorization: core.serialization.ObjectSchema<serializers.Authorization.Raw, Webflow.Authorization> =
    core.serialization.object({
        authorization: core.serialization
            .lazyObject(async () => (await import("..")).AuthorizationAuthorization)
            .optional(),
        application: core.serialization.lazy(async () => (await import("..")).Application).optional(),
    });

export declare namespace Authorization {
    interface Raw {
        authorization?: serializers.AuthorizationAuthorization.Raw | null;
        application?: (serializers.Application.Raw | undefined) | null;
    }
}
