/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";

export const CollectionItemRemovedPayloadFieldData: core.serialization.ObjectSchema<
    serializers.CollectionItemRemovedPayloadFieldData.Raw,
    Webflow.CollectionItemRemovedPayloadFieldData
> = core.serialization
    .object({
        name: core.serialization.string(),
        slug: core.serialization.string(),
    })
    .passthrough();

export declare namespace CollectionItemRemovedPayloadFieldData {
    interface Raw {
        name: string;
        slug: string;
        [key: string]: any;
    }
}
