/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { CollectionItem } from "./CollectionItem";

export const CollectionItemListNoPagination: core.serialization.ObjectSchema<
    serializers.CollectionItemListNoPagination.Raw,
    Webflow.CollectionItemListNoPagination
> = core.serialization.object({
    items: core.serialization.list(CollectionItem).optional(),
});

export declare namespace CollectionItemListNoPagination {
    interface Raw {
        items?: CollectionItem.Raw[] | null;
    }
}
