// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Field } from "./Field";

export const Collection: core.serialization.ObjectSchema<serializers.Collection.Raw, Webflow.Collection> =
    core.serialization.object({
        id: core.serialization.string(),
        displayName: core.serialization.string(),
        singularName: core.serialization.string(),
        slug: core.serialization.string().optional(),
        createdOn: core.serialization.date().optional(),
        lastUpdated: core.serialization.date().optional(),
        fields: core.serialization.list(Field),
    });

export declare namespace Collection {
    export interface Raw {
        id: string;
        displayName: string;
        singularName: string;
        slug?: string | null;
        createdOn?: string | null;
        lastUpdated?: string | null;
        fields: Field.Raw[];
    }
}
