// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import type * as core from "../../core";
import type * as serializers from "../index";
import { ComponentPropertyText } from "./ComponentPropertyText";

export const ComponentProperty: core.serialization.ObjectSchema<
    serializers.ComponentProperty.Raw,
    Webflow.ComponentProperty
> = ComponentPropertyText;

export declare namespace ComponentProperty {
    export type Raw = ComponentPropertyText.Raw;
}
