/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";

export const ComponentPropertyType: core.serialization.Schema<
    serializers.ComponentPropertyType.Raw,
    Webflow.ComponentPropertyType
> = core.serialization.enum_(["Plain Text", "Rich Text", "Alt Text"]);

export declare namespace ComponentPropertyType {
    export type Raw = "Plain Text" | "Rich Text" | "Alt Text";
}
