// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ComponentProperty } from "./ComponentProperty";

export const ComponentNode: core.serialization.ObjectSchema<serializers.ComponentNode.Raw, Webflow.ComponentNode> =
    core.serialization.object({
        id: core.serialization.string(),
        componentId: core.serialization.string(),
        propertyOverrides: core.serialization.list(ComponentProperty),
    });

export declare namespace ComponentNode {
    export interface Raw {
        id: string;
        componentId: string;
        propertyOverrides: ComponentProperty.Raw[];
    }
}
