/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { DuplicateUserEmail } from "./DuplicateUserEmail";
import { UserLimitReached } from "./UserLimitReached";

export const ConflictErrorBody: core.serialization.Schema<
    serializers.ConflictErrorBody.Raw,
    Webflow.ConflictErrorBody
> = core.serialization.undiscriminatedUnion([DuplicateUserEmail, UserLimitReached]);

export declare namespace ConflictErrorBody {
    export type Raw = (DuplicateUserEmail.Raw | undefined) | (UserLimitReached.Raw | undefined);
}
