// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CustomFontBatchDeleteResponseDeletedItem } from "./CustomFontBatchDeleteResponseDeletedItem";
import { CustomFontBatchDeleteResponseFailedItem } from "./CustomFontBatchDeleteResponseFailedItem";

export const CustomFontBatchDeleteResponse: core.serialization.ObjectSchema<
    serializers.CustomFontBatchDeleteResponse.Raw,
    Webflow.CustomFontBatchDeleteResponse
> = core.serialization.object({
    deleted: core.serialization.list(CustomFontBatchDeleteResponseDeletedItem),
    failed: core.serialization.list(CustomFontBatchDeleteResponseFailedItem),
});

export declare namespace CustomFontBatchDeleteResponse {
    export interface Raw {
        deleted: CustomFontBatchDeleteResponseDeletedItem.Raw[];
        failed: CustomFontBatchDeleteResponseFailedItem.Raw[];
    }
}
