// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CustomFont } from "./CustomFont";
import { CustomFontUpload } from "./CustomFontUpload";

export const CustomFontCreateResponse: core.serialization.ObjectSchema<
    serializers.CustomFontCreateResponse.Raw,
    Webflow.CustomFontCreateResponse
> = core.serialization.object({
    customFont: CustomFont,
    upload: CustomFontUpload,
});

export declare namespace CustomFontCreateResponse {
    export interface Raw {
        customFont: CustomFont.Raw;
        upload: CustomFontUpload.Raw;
    }
}
