// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CustomFontFontDisplay: core.serialization.Schema<
    serializers.CustomFontFontDisplay.Raw,
    Webflow.CustomFontFontDisplay
> = core.serialization.enum_(["auto", "block", "swap", "fallback", "optional"]);

export declare namespace CustomFontFontDisplay {
    export type Raw = "auto" | "block" | "swap" | "fallback" | "optional";
}
