/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";

export const FieldValidationsAdditionalPropertiesAdditionalProperties: core.serialization.ObjectSchema<
    serializers.FieldValidationsAdditionalPropertiesAdditionalProperties.Raw,
    Webflow.FieldValidationsAdditionalPropertiesAdditionalProperties
> = core.serialization.object({
    additionalProperties: core.serialization.unknown().optional(),
});

export declare namespace FieldValidationsAdditionalPropertiesAdditionalProperties {
    interface Raw {
        additionalProperties?: unknown | null;
    }
}
