// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { InvalidScopes } from "./InvalidScopes";
import { UsersNotEnabled } from "./UsersNotEnabled";

export const ForbiddenErrorBody: core.serialization.Schema<
    serializers.ForbiddenErrorBody.Raw,
    Webflow.ForbiddenErrorBody
> = core.serialization.undiscriminatedUnion([InvalidScopes, UsersNotEnabled]);

export declare namespace ForbiddenErrorBody {
    export type Raw = (InvalidScopes.Raw | undefined) | (UsersNotEnabled.Raw | undefined);
}
