// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const FormResponseSettings: core.serialization.ObjectSchema<
    serializers.FormResponseSettings.Raw,
    Webflow.FormResponseSettings
> = core.serialization.object({
    redirectUrl: core.serialization.string().optional(),
    redirectMethod: core.serialization.string().optional(),
    redirectAction: core.serialization.string().optional(),
    sendEmailConfirmation: core.serialization.boolean().optional(),
});

export declare namespace FormResponseSettings {
    export interface Raw {
        redirectUrl?: string | null;
        redirectMethod?: string | null;
        redirectAction?: string | null;
        sendEmailConfirmation?: boolean | null;
    }
}
