/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { FormSubmissionTriggerPayloadSchemaItemFieldType } from "./FormSubmissionTriggerPayloadSchemaItemFieldType";

export const FormSubmissionTriggerPayloadSchemaItem: core.serialization.ObjectSchema<
    serializers.FormSubmissionTriggerPayloadSchemaItem.Raw,
    Webflow.FormSubmissionTriggerPayloadSchemaItem
> = core.serialization.object({
    fieldName: core.serialization.string().optional(),
    fieldType: FormSubmissionTriggerPayloadSchemaItemFieldType.optional(),
    fieldElementId: core.serialization.string().optional(),
});

export declare namespace FormSubmissionTriggerPayloadSchemaItem {
    interface Raw {
        fieldName?: string | null;
        fieldType?: FormSubmissionTriggerPayloadSchemaItemFieldType.Raw | null;
        fieldElementId?: string | null;
    }
}
