/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";

export const InternalServerErrorBodyDetailsItem: core.serialization.Schema<
    serializers.InternalServerErrorBodyDetailsItem.Raw,
    Webflow.InternalServerErrorBodyDetailsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace InternalServerErrorBodyDetailsItem {
    type Raw = string | Record<string, unknown>;
}
