// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { InviteWorkspaceMemberRequestBodyEmailSiteAccessItemSiteRole } from "./InviteWorkspaceMemberRequestBodyEmailSiteAccessItemSiteRole";

export const InviteWorkspaceMemberRequestBodyEmailSiteAccessItem: core.serialization.ObjectSchema<
    serializers.InviteWorkspaceMemberRequestBodyEmailSiteAccessItem.Raw,
    Webflow.InviteWorkspaceMemberRequestBodyEmailSiteAccessItem
> = core.serialization.object({
    siteId: core.serialization.string(),
    siteRole: InviteWorkspaceMemberRequestBodyEmailSiteAccessItemSiteRole,
    siteRoleId: core.serialization.string().optional(),
});

export declare namespace InviteWorkspaceMemberRequestBodyEmailSiteAccessItem {
    export interface Raw {
        siteId: string;
        siteRole: InviteWorkspaceMemberRequestBodyEmailSiteAccessItemSiteRole.Raw;
        siteRoleId?: string | null;
    }
}
