// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const ItemsListItemsLiveRequestCreatedOn: core.serialization.ObjectSchema<
    serializers.ItemsListItemsLiveRequestCreatedOn.Raw,
    Webflow.ItemsListItemsLiveRequestCreatedOn
> = core.serialization.object({
    lte: core.serialization.date().optional(),
    gte: core.serialization.date().optional(),
});

export declare namespace ItemsListItemsLiveRequestCreatedOn {
    export interface Raw {
        lte?: string | null;
        gte?: string | null;
    }
}
