/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { Locale } from "./Locale";

export const Locales: core.serialization.ObjectSchema<serializers.Locales.Raw, Webflow.Locales> =
    core.serialization.object({
        primary: Locale.optional(),
        secondary: core.serialization.list(Locale).optional(),
    });

export declare namespace Locales {
    export interface Raw {
        primary?: Locale.Raw | null;
        secondary?: Locale.Raw[] | null;
    }
}
