// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { ComponentNode } from "./ComponentNode";
import { ImageNode } from "./ImageNode";
import { SearchButtonNode } from "./SearchButtonNode";
import { SelectNode } from "./SelectNode";
import { SubmitButtonNode } from "./SubmitButtonNode";
import { TextInputNode } from "./TextInputNode";
import { TextNode } from "./TextNode";

export const Node: core.serialization.Schema<serializers.Node.Raw, Webflow.Node> = core.serialization
    .union("type", {
        text: TextNode,
        image: ImageNode,
        "component-instance": ComponentNode,
        "text-input": TextInputNode,
        select: SelectNode,
        "submit-button": SubmitButtonNode,
        "search-button": SearchButtonNode,
    })
    .transform<Webflow.Node>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Node {
    export type Raw =
        | Node.Text
        | Node.Image
        | Node.ComponentInstance
        | Node.TextInput
        | Node.Select
        | Node.SubmitButton
        | Node.SearchButton;

    export interface Text extends TextNode.Raw {
        type: "text";
    }

    export interface Image extends ImageNode.Raw {
        type: "image";
    }

    export interface ComponentInstance extends ComponentNode.Raw {
        type: "component-instance";
    }

    export interface TextInput extends TextInputNode.Raw {
        type: "text-input";
    }

    export interface Select extends SelectNode.Raw {
        type: "select";
    }

    export interface SubmitButton extends SubmitButtonNode.Raw {
        type: "submit-button";
    }

    export interface SearchButton extends SearchButtonNode.Raw {
        type: "search-button";
    }
}
