/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { NodeType } from "./NodeType";
import { TextNode } from "./TextNode";
import { ImageNode } from "./ImageNode";

export const Node: core.serialization.ObjectSchema<serializers.Node.Raw, Webflow.Node> = core.serialization.object({
    id: core.serialization.string().optional(),
    type: NodeType.optional(),
    text: TextNode.optional(),
    image: ImageNode.optional(),
    attributes: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace Node {
    interface Raw {
        id?: string | null;
        type?: NodeType.Raw | null;
        text?: TextNode.Raw | null;
        image?: ImageNode.Raw | null;
        attributes?: Record<string, string> | null;
    }
}
