/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { NotFoundErrorBodyCode } from "./NotFoundErrorBodyCode";
import { NotFoundErrorBodyDetailsItem } from "./NotFoundErrorBodyDetailsItem";

export const NotFoundErrorBody: core.serialization.ObjectSchema<
    serializers.NotFoundErrorBody.Raw,
    Webflow.NotFoundErrorBody
> = core.serialization.object({
    code: NotFoundErrorBodyCode.optional(),
    message: core.serialization.string().optional(),
    externalReference: core.serialization.string().optional(),
    details: core.serialization.list(NotFoundErrorBodyDetailsItem).optional(),
});

export declare namespace NotFoundErrorBody {
    interface Raw {
        code?: NotFoundErrorBodyCode.Raw | null;
        message?: string | null;
        externalReference?: string | null;
        details?: NotFoundErrorBodyDetailsItem.Raw[] | null;
    }
}
