/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Webflow from "../../api";
import * as core from "../../core";

export const OrderPurchasedItemVariantImageFileVariantsItem: core.serialization.ObjectSchema<
    serializers.OrderPurchasedItemVariantImageFileVariantsItem.Raw,
    Webflow.OrderPurchasedItemVariantImageFileVariantsItem
> = core.serialization.object({
    url: core.serialization.string().optional(),
    originalFileName: core.serialization.string().optional(),
    size: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
});

export declare namespace OrderPurchasedItemVariantImageFileVariantsItem {
    interface Raw {
        url?: string | null;
        originalFileName?: string | null;
        size?: number | null;
        width?: number | null;
        height?: number | null;
    }
}
