/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Webflow from "../../api";
import * as core from "../../core";

export const PageSeoGraphData: core.serialization.ObjectSchema<
    serializers.PageSeoGraphData.Raw,
    Webflow.PageSeoGraphData
> = core.serialization.object({
    seo: core.serialization.lazyObject(async () => (await import("..")).PageSeoGraphDataSeo).optional(),
    openGraph: core.serialization.lazyObject(async () => (await import("..")).PageSeoGraphDataOpenGraph).optional(),
});

export declare namespace PageSeoGraphData {
    interface Raw {
        seo?: serializers.PageSeoGraphDataSeo.Raw | null;
        openGraph?: serializers.PageSeoGraphDataOpenGraph.Raw | null;
    }
}
