// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Pagination } from "./Pagination";
import { Redirect } from "./Redirect";

export const Redirects: core.serialization.ObjectSchema<serializers.Redirects.Raw, Webflow.Redirects> =
    core.serialization.object({
        redirects: core.serialization.list(Redirect).optional(),
        pagination: Pagination.optional(),
    });

export declare namespace Redirects {
    export interface Raw {
        redirects?: Redirect.Raw[] | null;
        pagination?: Pagination.Raw | null;
    }
}
