// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CustomCodeHostedResponse } from "./CustomCodeHostedResponse";
import { Pagination } from "./Pagination";

export const RegisteredScriptList: core.serialization.ObjectSchema<
    serializers.RegisteredScriptList.Raw,
    Webflow.RegisteredScriptList
> = core.serialization.object({
    registeredScripts: core.serialization.list(CustomCodeHostedResponse).optional(),
    pagination: Pagination.optional(),
});

export declare namespace RegisteredScriptList {
    export interface Raw {
        registeredScripts?: CustomCodeHostedResponse.Raw[] | null;
        pagination?: Pagination.Raw | null;
    }
}
