// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Pagination } from "./Pagination";
import { SiteActivityLogItem } from "./SiteActivityLogItem";

export const SiteActivityLogResponse: core.serialization.ObjectSchema<
    serializers.SiteActivityLogResponse.Raw,
    Webflow.SiteActivityLogResponse
> = core.serialization.object({
    items: core.serialization.list(SiteActivityLogItem).optional(),
    pagination: Pagination.optional(),
});

export declare namespace SiteActivityLogResponse {
    export interface Raw {
        items?: SiteActivityLogItem.Raw[] | null;
        pagination?: Pagination.Raw | null;
    }
}
