// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SiteMemberRolesSite: core.serialization.Schema<
    serializers.SiteMemberRolesSite.Raw,
    Webflow.SiteMemberRolesSite
> = core.serialization.enum_([
    "site_manager",
    "designer",
    "branch_designer",
    "limited_designer",
    "marketer",
    "content_editor",
    "reviewer",
    "viewer",
    "custom",
]);

export declare namespace SiteMemberRolesSite {
    export type Raw =
        | "site_manager"
        | "designer"
        | "branch_designer"
        | "limited_designer"
        | "marketer"
        | "content_editor"
        | "reviewer"
        | "viewer"
        | "custom";
}
