/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Webflow from "../../api";
import * as core from "../../core";

export const SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus: core.serialization.Schema<
    serializers.SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus.Raw,
    Webflow.SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus
> = core.serialization.enum_(["active", "inactive", "canceled"]);

export declare namespace SkuFieldDataEcSkuSubscriptionPlanPlansItemStatus {
    type Raw = "active" | "inactive" | "canceled";
}
