/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Webflow from "../../api";
import * as core from "../../core";

export const SkuFieldDataEcSkuSubscriptionPlan: core.serialization.ObjectSchema<
    serializers.SkuFieldDataEcSkuSubscriptionPlan.Raw,
    Webflow.SkuFieldDataEcSkuSubscriptionPlan
> = core.serialization.object({
    interval: core.serialization
        .lazy(async () => (await import("..")).SkuFieldDataEcSkuSubscriptionPlanInterval)
        .optional(),
    frequency: core.serialization.number().optional(),
    trial: core.serialization.number().optional(),
    plans: core.serialization
        .list(
            core.serialization.lazyObject(async () => (await import("..")).SkuFieldDataEcSkuSubscriptionPlanPlansItem)
        )
        .optional(),
});

export declare namespace SkuFieldDataEcSkuSubscriptionPlan {
    interface Raw {
        interval?: serializers.SkuFieldDataEcSkuSubscriptionPlanInterval.Raw | null;
        frequency?: number | null;
        trial?: number | null;
        plans?: serializers.SkuFieldDataEcSkuSubscriptionPlanPlansItem.Raw[] | null;
    }
}
