/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { SkuValueList } from "./SkuValueList";
import { SkuFieldDataPrice } from "./SkuFieldDataPrice";
import { SkuFieldDataCompareAtPrice } from "./SkuFieldDataCompareAtPrice";
import { SkuFieldDataEcSkuBillingMethod } from "./SkuFieldDataEcSkuBillingMethod";
import { SkuFieldDataEcSkuSubscriptionPlan } from "./SkuFieldDataEcSkuSubscriptionPlan";
import { SkuPropertyList } from "./SkuPropertyList";

export const SkuFieldData: core.serialization.ObjectSchema<serializers.SkuFieldData.Raw, Webflow.SkuFieldData> =
    core.serialization.object({
        skuValues: core.serialization.property("sku-values", SkuValueList.optional()),
        name: core.serialization.string(),
        slug: core.serialization.string(),
        price: SkuFieldDataPrice,
        compareAtPrice: core.serialization.property("compare-at-price", SkuFieldDataCompareAtPrice.optional()),
        ecSkuBillingMethod: core.serialization.property(
            "ec-sku-billing-method",
            SkuFieldDataEcSkuBillingMethod.optional()
        ),
        ecSkuSubscriptionPlan: core.serialization.property(
            "ec-sku-subscription-plan",
            SkuFieldDataEcSkuSubscriptionPlan.optional()
        ),
        trackInventory: core.serialization.property("track-inventory", core.serialization.boolean().optional()),
        quantity: core.serialization.number().optional(),
        mainImage: core.serialization.property("main-image", core.serialization.string().optional()),
        sku: core.serialization.string().optional(),
        skuProperties: core.serialization.property(
            "sku-properties",
            core.serialization.list(SkuPropertyList).optional()
        ),
    });

export declare namespace SkuFieldData {
    interface Raw {
        "sku-values"?: SkuValueList.Raw | null;
        name: string;
        slug: string;
        price: SkuFieldDataPrice.Raw;
        "compare-at-price"?: SkuFieldDataCompareAtPrice.Raw | null;
        "ec-sku-billing-method"?: SkuFieldDataEcSkuBillingMethod.Raw | null;
        "ec-sku-subscription-plan"?: SkuFieldDataEcSkuSubscriptionPlan.Raw | null;
        "track-inventory"?: boolean | null;
        quantity?: number | null;
        "main-image"?: string | null;
        sku?: string | null;
        "sku-properties"?: SkuPropertyList.Raw[] | null;
    }
}
