// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SkuFieldDataEcSkuBillingMethod: core.serialization.Schema<
    serializers.SkuFieldDataEcSkuBillingMethod.Raw,
    Webflow.SkuFieldDataEcSkuBillingMethod
> = core.serialization.enum_(["one-time", "subscription"]);

export declare namespace SkuFieldDataEcSkuBillingMethod {
    export type Raw = "one-time" | "subscription";
}
