// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const StaticFieldType: core.serialization.Schema<serializers.StaticFieldType.Raw, Webflow.StaticFieldType> =
    core.serialization.enum_([
        "Color",
        "DateTime",
        "Email",
        "File",
        "Image",
        "Link",
        "MultiImage",
        "Number",
        "Phone",
        "PlainText",
        "RichText",
        "Switch",
        "VideoLink",
    ]);

export declare namespace StaticFieldType {
    export type Raw =
        | "Color"
        | "DateTime"
        | "Email"
        | "File"
        | "Image"
        | "Link"
        | "MultiImage"
        | "Number"
        | "Phone"
        | "PlainText"
        | "RichText"
        | "Switch"
        | "VideoLink";
}
