// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TextInputNodeWrite: core.serialization.ObjectSchema<
    serializers.TextInputNodeWrite.Raw,
    Webflow.TextInputNodeWrite
> = core.serialization.object({
    nodeId: core.serialization.string(),
    placeholder: core.serialization.string(),
});

export declare namespace TextInputNodeWrite {
    export interface Raw {
        nodeId: string;
        placeholder: string;
    }
}
