/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { TextNodeText } from "./TextNodeText";

export const TextNodeDom: core.serialization.ObjectSchema<serializers.TextNodeDom.Raw, Webflow.TextNodeDom> =
    core.serialization.object({
        id: core.serialization.string(),
        text: TextNodeText,
        attributes: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    });

export declare namespace TextNodeDom {
    export interface Raw {
        id: string;
        text: TextNodeText.Raw;
        attributes?: Record<string, string> | null;
    }
}
