// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TopEventsCmsContextEntry: core.serialization.ObjectSchema<
    serializers.TopEventsCmsContextEntry.Raw,
    Webflow.TopEventsCmsContextEntry
> = core.serialization.object({
    collectionId: core.serialization.string(),
    itemId: core.serialization.string(),
});

export declare namespace TopEventsCmsContextEntry {
    export interface Raw {
        collectionId: string;
        itemId: string;
    }
}
