// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TopEventsTimeseriesPoint: core.serialization.ObjectSchema<
    serializers.TopEventsTimeseriesPoint.Raw,
    Webflow.TopEventsTimeseriesPoint
> = core.serialization.object({
    timestamp: core.serialization.date(),
    count: core.serialization.number(),
});

export declare namespace TopEventsTimeseriesPoint {
    export interface Raw {
        timestamp: string;
        count: number;
    }
}
