// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TopPagesSortBy: core.serialization.Schema<serializers.TopPagesSortBy.Raw, Webflow.TopPagesSortBy> =
    core.serialization.enum_(["session", "user", "pageview"]);

export declare namespace TopPagesSortBy {
    export type Raw = "session" | "user" | "pageview";
}
