/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";

export const WebhookFilter: core.serialization.ObjectSchema<serializers.WebhookFilter.Raw, Webflow.WebhookFilter> =
    core.serialization.object({
        name: core.serialization.string().optional(),
    });

export declare namespace WebhookFilter {
    export interface Raw {
        name?: string | null;
    }
}
