/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUser } from "./WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUser";
import { WorkspaceAuditLogItemPayloadWorkspaceInvitationMethod } from "./WorkspaceAuditLogItemPayloadWorkspaceInvitationMethod";
import { WorkspaceAuditLogItemPayloadWorkspaceInvitationUserType } from "./WorkspaceAuditLogItemPayloadWorkspaceInvitationUserType";
import { WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUsersItem } from "./WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUsersItem";

export const WorkspaceInvitation: core.serialization.ObjectSchema<
    serializers.WorkspaceInvitation.Raw,
    Webflow.WorkspaceInvitation
> = core.serialization.object({
    targetUser: WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUser.optional(),
    method: WorkspaceAuditLogItemPayloadWorkspaceInvitationMethod.optional(),
    userType: WorkspaceAuditLogItemPayloadWorkspaceInvitationUserType.optional(),
    roleName: core.serialization.string().optional(),
    previousRoleName: core.serialization.string().optional(),
    targetUsers: core.serialization.list(WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUsersItem).optional(),
});

export declare namespace WorkspaceInvitation {
    export interface Raw {
        targetUser?: WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUser.Raw | null;
        method?: WorkspaceAuditLogItemPayloadWorkspaceInvitationMethod.Raw | null;
        userType?: WorkspaceAuditLogItemPayloadWorkspaceInvitationUserType.Raw | null;
        roleName?: string | null;
        previousRoleName?: string | null;
        targetUsers?: WorkspaceAuditLogItemPayloadWorkspaceInvitationTargetUsersItem.Raw[] | null;
    }
}
