// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const WorkspaceAuditLogItemPayloadWorkspaceMembershipMethod: core.serialization.Schema<
    serializers.WorkspaceAuditLogItemPayloadWorkspaceMembershipMethod.Raw,
    Webflow.WorkspaceAuditLogItemPayloadWorkspaceMembershipMethod
> = core.serialization.enum_(["sso", "dashboard", "admin", "access_request"]);

export declare namespace WorkspaceAuditLogItemPayloadWorkspaceMembershipMethod {
    export type Raw = "sso" | "dashboard" | "admin" | "access_request";
}
