// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const WorkspaceAuditLogItemPayloadWorkspaceMembershipTargetUser: core.serialization.ObjectSchema<
    serializers.WorkspaceAuditLogItemPayloadWorkspaceMembershipTargetUser.Raw,
    Webflow.WorkspaceAuditLogItemPayloadWorkspaceMembershipTargetUser
> = core.serialization.object({
    id: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
});

export declare namespace WorkspaceAuditLogItemPayloadWorkspaceMembershipTargetUser {
    export interface Raw {
        id?: string | null;
        email?: string | null;
    }
}
