/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Webflow from "../../api/index";
import * as core from "../../core";
import { WorkspaceMembershipAuditLogItemEventSubType } from "./WorkspaceMembershipAuditLogItemEventSubType";
import { WorkspaceMembership } from "./WorkspaceMembership";

export const WorkspaceMembershipAuditLogItem: core.serialization.ObjectSchema<
    serializers.WorkspaceMembershipAuditLogItem.Raw,
    Webflow.WorkspaceMembershipAuditLogItem
> = core.serialization.object({
    eventSubType: WorkspaceMembershipAuditLogItemEventSubType.optional(),
    payload: WorkspaceMembership.optional(),
});

export declare namespace WorkspaceMembershipAuditLogItem {
    export interface Raw {
        eventSubType?: WorkspaceMembershipAuditLogItemEventSubType.Raw | null;
        payload?: WorkspaceMembership.Raw | null;
    }
}
