/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const ProductsListResponseItemsItemSkusItemFieldDataEcSkuBillingMethod: core.serialization.Schema<
    serializers.ProductsListResponseItemsItemSkusItemFieldDataEcSkuBillingMethod.Raw,
    Webflow.ProductsListResponseItemsItemSkusItemFieldDataEcSkuBillingMethod
> = core.serialization.enum_(["one-time", "subscription"]);

export declare namespace ProductsListResponseItemsItemSkusItemFieldDataEcSkuBillingMethod {
    type Raw = "one-time" | "subscription";
}
