/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const ProductsCreateResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus: core.serialization.Schema<
    serializers.ProductsCreateResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus.Raw,
    Webflow.ProductsCreateResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus
> = core.serialization.enum_(["active", "inactive", "canceled"]);

export declare namespace ProductsCreateResponseSkusItemFieldDataEcSkuSubscriptionPlanPlansItemStatus {
    type Raw = "active" | "inactive" | "canceled";
}
