/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { ProductsUpdateRequestProductFieldDataSkuPropertiesItemEnumItem } from "./ProductsUpdateRequestProductFieldDataSkuPropertiesItemEnumItem";

export const ProductsUpdateRequestProductFieldDataSkuPropertiesItem: core.serialization.ObjectSchema<
    serializers.ProductsUpdateRequestProductFieldDataSkuPropertiesItem.Raw,
    Webflow.ProductsUpdateRequestProductFieldDataSkuPropertiesItem
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    enum: core.serialization.list(ProductsUpdateRequestProductFieldDataSkuPropertiesItemEnumItem),
});

export declare namespace ProductsUpdateRequestProductFieldDataSkuPropertiesItem {
    interface Raw {
        id: string;
        name: string;
        enum: ProductsUpdateRequestProductFieldDataSkuPropertiesItemEnumItem.Raw[];
    }
}
