/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const ProductsListResponseItemsItemSkusItemFieldDataEcSkuSubscriptionPlanInterval: core.serialization.Schema<
    serializers.ProductsListResponseItemsItemSkusItemFieldDataEcSkuSubscriptionPlanInterval.Raw,
    Webflow.ProductsListResponseItemsItemSkusItemFieldDataEcSkuSubscriptionPlanInterval
> = core.serialization.enum_(["day", "week", "month", "year"]);

export declare namespace ProductsListResponseItemsItemSkusItemFieldDataEcSkuSubscriptionPlanInterval {
    type Raw = "day" | "week" | "month" | "year";
}
