/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Webflow from "../../../../api";
import * as core from "../../../../core";

export const ProductSkuCreateSkuFieldData: core.serialization.ObjectSchema<
    serializers.ProductSkuCreateSkuFieldData.Raw,
    Webflow.ProductSkuCreateSkuFieldData
> = core.serialization.object({
    skuValues: core.serialization.property(
        "sku-values",
        core.serialization.lazy(async () => (await import("../../..")).SkuValueList).optional()
    ),
    name: core.serialization.string(),
    slug: core.serialization.string(),
    price: core.serialization.lazyObject(async () => (await import("../../..")).ProductSkuCreateSkuFieldDataPrice),
    compareAtPrice: core.serialization.property(
        "compare-at-price",
        core.serialization
            .lazyObject(async () => (await import("../../..")).ProductSkuCreateSkuFieldDataCompareAtPrice)
            .optional()
    ),
    ecSkuBillingMethod: core.serialization.property(
        "ec-sku-billing-method",
        core.serialization
            .lazy(async () => (await import("../../..")).ProductSkuCreateSkuFieldDataEcSkuBillingMethod)
            .optional()
    ),
    ecSkuSubscriptionPlan: core.serialization.property(
        "ec-sku-subscription-plan",
        core.serialization
            .lazyObject(async () => (await import("../../..")).ProductSkuCreateSkuFieldDataEcSkuSubscriptionPlan)
            .optional()
    ),
    trackInventory: core.serialization.property("track-inventory", core.serialization.boolean().optional()),
    quantity: core.serialization.number().optional(),
});

export declare namespace ProductSkuCreateSkuFieldData {
    interface Raw {
        "sku-values"?: serializers.SkuValueList.Raw | null;
        name: string;
        slug: string;
        price: serializers.ProductSkuCreateSkuFieldDataPrice.Raw;
        "compare-at-price"?: serializers.ProductSkuCreateSkuFieldDataCompareAtPrice.Raw | null;
        "ec-sku-billing-method"?: serializers.ProductSkuCreateSkuFieldDataEcSkuBillingMethod.Raw | null;
        "ec-sku-subscription-plan"?: serializers.ProductSkuCreateSkuFieldDataEcSkuSubscriptionPlan.Raw | null;
        "track-inventory"?: boolean | null;
        quantity?: number | null;
    }
}
