/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Webflow from "../../../../../../index";

/**
 * @example
 *     {
 *         isRequired: false,
 *         type: "RichText",
 *         displayName: "Post Body",
 *         helpText: "Add the body of your post here"
 *     }
 */
export interface FieldsCreateRequest {
    /** define whether a field is required in a collection */
    isRequired?: boolean;
    /** Choose these appropriate field type for your collection data */
    type: Webflow.collections.FieldsCreateRequestType;
    /** The name of a field */
    displayName: string;
    /** Additional text to help anyone filling out this field */
    helpText?: string;
}
