// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const ItemsListItemsLiveRequestSortValue: core.serialization.Schema<
    serializers.collections.ItemsListItemsLiveRequestSortValue.Raw,
    Webflow.collections.ItemsListItemsLiveRequestSortValue
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace ItemsListItemsLiveRequestSortValue {
    export type Raw = "asc" | "desc";
}
