/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Webflow from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { ItemsUpdateItemsLiveRequestItemsItemFieldData } from "./ItemsUpdateItemsLiveRequestItemsItemFieldData";

export const ItemsUpdateItemsLiveRequestItemsItem: core.serialization.ObjectSchema<
    serializers.collections.ItemsUpdateItemsLiveRequestItemsItem.Raw,
    Webflow.collections.ItemsUpdateItemsLiveRequestItemsItem
> = core.serialization.object({
    id: core.serialization.string(),
    cmsLocaleId: core.serialization.string().optional(),
    isArchived: core.serialization.boolean().optional(),
    isDraft: core.serialization.boolean().optional(),
    fieldData: ItemsUpdateItemsLiveRequestItemsItemFieldData.optional(),
});

export declare namespace ItemsUpdateItemsLiveRequestItemsItem {
    interface Raw {
        id: string;
        cmsLocaleId?: string | null;
        isArchived?: boolean | null;
        isDraft?: boolean | null;
        fieldData?: ItemsUpdateItemsLiveRequestItemsItemFieldData.Raw | null;
    }
}
