// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";
import { CollectionItemPostSingle } from "../../../../../types/CollectionItemPostSingle";

export const MultipleItems: core.serialization.ObjectSchema<
    serializers.collections.MultipleItems.Raw,
    Webflow.collections.MultipleItems
> = core.serialization.object({
    items: core.serialization.list(CollectionItemPostSingle).optional(),
});

export declare namespace MultipleItems {
    export interface Raw {
        items?: CollectionItemPostSingle.Raw[] | null;
    }
}
