// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../../../api/index";
import * as core from "../../../../../../core";
import type * as serializers from "../../../../../index";

export const SingleCmsItem: core.serialization.ObjectSchema<
    serializers.collections.SingleCmsItem.Raw,
    Webflow.collections.SingleCmsItem
> = core.serialization
    .object({
        name: core.serialization.string(),
        slug: core.serialization.string(),
    })
    .passthrough();

export declare namespace SingleCmsItem {
    export interface Raw {
        name: string;
        slug: string;
        [key: string]: any;
    }
}
