/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Webflow from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { CollectionItemWithIdInput } from "../../../../../../types/CollectionItemWithIdInput";

export const ItemsUpdateItemsRequest: core.serialization.Schema<
    serializers.collections.ItemsUpdateItemsRequest.Raw,
    Omit<Webflow.collections.ItemsUpdateItemsRequest, "skipInvalidFiles">
> = core.serialization.object({
    items: core.serialization.list(CollectionItemWithIdInput).optional(),
});

export declare namespace ItemsUpdateItemsRequest {
    export interface Raw {
        items?: CollectionItemWithIdInput.Raw[] | null;
    }
}
