/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Webflow from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { ItemsDeleteItemsRequestItemsItem } from "../../types/ItemsDeleteItemsRequestItemsItem";

export const ItemsDeleteItemsRequest: core.serialization.Schema<
    serializers.collections.ItemsDeleteItemsRequest.Raw,
    Webflow.collections.ItemsDeleteItemsRequest
> = core.serialization.object({
    items: core.serialization.list(ItemsDeleteItemsRequestItemsItem),
});

export declare namespace ItemsDeleteItemsRequest {
    export interface Raw {
        items: ItemsDeleteItemsRequestItemsItem.Raw[];
    }
}
