/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Webflow from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const WellKnownDeleteRequest: core.serialization.Schema<
    serializers.sites.WellKnownDeleteRequest.Raw,
    Webflow.sites.WellKnownDeleteRequest
> = core.serialization.object({
    fileNames: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace WellKnownDeleteRequest {
    export interface Raw {
        fileNames?: string[] | null;
    }
}
