// This file was auto-generated by Fern from our API Definition.

import * as Webflow from "../../src/api/index";
import { WebflowClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Products", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {
            items: [
                {
                    product: {
                        id: "660eb7a486d1d6e0412292d7",
                        cmsLocaleId: "653ad57de882f528b32e810e",
                        lastPublished: "2024-04-04T14:24:19Z",
                        lastUpdated: "2024-04-04T14:30:19Z",
                        createdOn: "2024-04-04T14:22:28Z",
                        isArchived: false,
                        isDraft: false,
                        fieldData: {
                            name: "T-Shirt",
                            slug: "t-shirt",
                            description: "A plain cotton t-shirt.",
                            shippable: true,
                            "sku-properties": [
                                {
                                    id: "Color",
                                    name: "Color",
                                    enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                                },
                            ],
                        },
                    },
                    skus: [
                        {
                            id: "66072fb71b89448912e2681c",
                            cmsLocaleId: "653ad57de882f528b32e810e",
                            lastPublished: "2023-03-17T18:47:35Z",
                            lastUpdated: "2023-03-17T18:47:35Z",
                            createdOn: "2023-03-17T18:47:35Z",
                            fieldData: {
                                "sku-values": { color: "blue", size: "small" },
                                name: "Colorful T-shirt - Default",
                                slug: "colorful-t-shirt-default",
                                price: { value: 2499, unit: "USD", currency: "USD" },
                                "main-image": "https://www.example.com/image.jpg",
                                sku: "1234567890",
                                "sku-properties": [
                                    {
                                        id: "Color",
                                        name: "Color",
                                        enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                                    },
                                ],
                            },
                        },
                    ],
                },
            ],
            pagination: { limit: 100, offset: 0, total: 100 },
        };
        server
            .mockEndpoint()
            .get("/sites/580e63e98c9a982ac9b8b741/products")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.list("580e63e98c9a982ac9b8b741", {
            offset: 1.1,
            limit: 1.1,
        });
        expect(response).toEqual({
            items: [
                {
                    product: {
                        id: "660eb7a486d1d6e0412292d7",
                        cmsLocaleId: "653ad57de882f528b32e810e",
                        lastPublished: new Date("2024-04-04T14:24:19.000Z"),
                        lastUpdated: new Date("2024-04-04T14:30:19.000Z"),
                        createdOn: new Date("2024-04-04T14:22:28.000Z"),
                        isArchived: false,
                        isDraft: false,
                        fieldData: {
                            name: "T-Shirt",
                            slug: "t-shirt",
                            description: "A plain cotton t-shirt.",
                            shippable: true,
                            skuProperties: [
                                {
                                    id: "Color",
                                    name: "Color",
                                    enum: [
                                        {
                                            id: "royal-blue",
                                            name: "Royal Blue",
                                            slug: "royal-blue",
                                        },
                                    ],
                                },
                            ],
                        },
                    },
                    skus: [
                        {
                            id: "66072fb71b89448912e2681c",
                            cmsLocaleId: "653ad57de882f528b32e810e",
                            lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                            lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                            createdOn: new Date("2023-03-17T18:47:35.000Z"),
                            fieldData: {
                                skuValues: {
                                    color: "blue",
                                    size: "small",
                                },
                                name: "Colorful T-shirt - Default",
                                slug: "colorful-t-shirt-default",
                                price: {
                                    value: 2499,
                                    unit: "USD",
                                    currency: "USD",
                                },
                                mainImage: "https://www.example.com/image.jpg",
                                sku: "1234567890",
                                skuProperties: [
                                    {
                                        id: "Color",
                                        name: "Color",
                                        enum: [
                                            {
                                                id: "royal-blue",
                                                name: "Royal Blue",
                                                slug: "royal-blue",
                                            },
                                        ],
                                    },
                                ],
                            },
                        },
                    ],
                },
            ],
            pagination: {
                limit: 100,
                offset: 0,
                total: 100,
            },
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.list("site_id");
        }).rejects.toThrow(Webflow.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {
            publishStatus: "staging",
            product: {
                fieldData: {
                    name: "Colorful T-shirt",
                    slug: "colorful-t-shirt",
                    description: "Our best-selling t-shirt available in multiple colors and sizes",
                    "sku-properties": [
                        {
                            id: "color",
                            name: "Color",
                            enum: [
                                { id: "red", name: "Red", slug: "red" },
                                { id: "yellow", name: "Yellow", slug: "yellow" },
                                { id: "blue", name: "Blue", slug: "blue" },
                            ],
                        },
                        {
                            id: "size",
                            name: "Size",
                            enum: [
                                { id: "small", name: "Small", slug: "small" },
                                { id: "medium", name: "Medium", slug: "medium" },
                                { id: "large", name: "Large", slug: "large" },
                            ],
                        },
                    ],
                },
            },
            sku: {
                fieldData: {
                    name: "Colorful T-shirt - Red Small",
                    slug: "colorful-t-shirt-red-small",
                    price: { value: 2499, unit: "USD", currency: "USD" },
                    "main-image":
                        "https://rocketamp-sample-store.myshopify.com/cdn/shop/products/Gildan_2000_Antique_Cherry_Red_Front_1024x1024.jpg?v=1527232987",
                },
            },
        };
        const rawResponseBody = {
            product: {
                id: "660eb7a486d1d6e0412292d7",
                cmsLocaleId: "653ad57de882f528b32e810e",
                lastPublished: "2024-04-04T14:24:19Z",
                lastUpdated: "2024-04-04T14:30:19Z",
                createdOn: "2024-04-04T14:22:28Z",
                isArchived: false,
                isDraft: false,
                fieldData: {
                    name: "T-Shirt",
                    slug: "t-shirt",
                    description: "A plain cotton t-shirt.",
                    shippable: true,
                    "sku-properties": [
                        {
                            id: "Color",
                            name: "Color",
                            enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                        },
                    ],
                    category: ["category"],
                    "tax-category": "standard-taxable",
                    "default-sku": "default-sku",
                    "ec-product-type": "ff42fee0113744f693a764e3431a9cc2",
                },
            },
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: "2023-03-17T18:47:35Z",
                    lastUpdated: "2023-03-17T18:47:35Z",
                    createdOn: "2023-03-17T18:47:35Z",
                    fieldData: {
                        "sku-values": { color: "blue", size: "small" },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: { value: 2499, unit: "USD", currency: "USD" },
                        "main-image": "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        "sku-properties": [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                            },
                        ],
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/sites/580e63e98c9a982ac9b8b741/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.create("580e63e98c9a982ac9b8b741", {
            publishStatus: "staging",
            product: {
                fieldData: {
                    name: "Colorful T-shirt",
                    slug: "colorful-t-shirt",
                    description: "Our best-selling t-shirt available in multiple colors and sizes",
                    skuProperties: [
                        {
                            id: "color",
                            name: "Color",
                            enum: [
                                {
                                    id: "red",
                                    name: "Red",
                                    slug: "red",
                                },
                                {
                                    id: "yellow",
                                    name: "Yellow",
                                    slug: "yellow",
                                },
                                {
                                    id: "blue",
                                    name: "Blue",
                                    slug: "blue",
                                },
                            ],
                        },
                        {
                            id: "size",
                            name: "Size",
                            enum: [
                                {
                                    id: "small",
                                    name: "Small",
                                    slug: "small",
                                },
                                {
                                    id: "medium",
                                    name: "Medium",
                                    slug: "medium",
                                },
                                {
                                    id: "large",
                                    name: "Large",
                                    slug: "large",
                                },
                            ],
                        },
                    ],
                },
            },
            sku: {
                fieldData: {
                    name: "Colorful T-shirt - Red Small",
                    slug: "colorful-t-shirt-red-small",
                    price: {
                        value: 2499,
                        unit: "USD",
                        currency: "USD",
                    },
                    mainImage:
                        "https://rocketamp-sample-store.myshopify.com/cdn/shop/products/Gildan_2000_Antique_Cherry_Red_Front_1024x1024.jpg?v=1527232987",
                },
            },
        });
        expect(response).toEqual({
            product: {
                id: "660eb7a486d1d6e0412292d7",
                cmsLocaleId: "653ad57de882f528b32e810e",
                lastPublished: new Date("2024-04-04T14:24:19.000Z"),
                lastUpdated: new Date("2024-04-04T14:30:19.000Z"),
                createdOn: new Date("2024-04-04T14:22:28.000Z"),
                isArchived: false,
                isDraft: false,
                fieldData: {
                    name: "T-Shirt",
                    slug: "t-shirt",
                    description: "A plain cotton t-shirt.",
                    shippable: true,
                    skuProperties: [
                        {
                            id: "Color",
                            name: "Color",
                            enum: [
                                {
                                    id: "royal-blue",
                                    name: "Royal Blue",
                                    slug: "royal-blue",
                                },
                            ],
                        },
                    ],
                    category: ["category"],
                    taxCategory: "standard-taxable",
                    defaultSku: "default-sku",
                    ecProductType: "ff42fee0113744f693a764e3431a9cc2",
                },
            },
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                    lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                    createdOn: new Date("2023-03-17T18:47:35.000Z"),
                    fieldData: {
                        skuValues: {
                            color: "blue",
                            size: "small",
                        },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: {
                            value: 2499,
                            unit: "USD",
                            currency: "USD",
                        },
                        mainImage: "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        skuProperties: [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [
                                    {
                                        id: "royal-blue",
                                        name: "Royal Blue",
                                        slug: "royal-blue",
                                    },
                                ],
                            },
                        ],
                    },
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { product: {}, sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.create("site_id", {
                product: {},
                sku: {},
            });
        }).rejects.toThrow(Webflow.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {
            product: {
                id: "660eb7a486d1d6e0412292d7",
                cmsLocaleId: "653ad57de882f528b32e810e",
                lastPublished: "2024-04-04T14:24:19Z",
                lastUpdated: "2024-04-04T14:30:19Z",
                createdOn: "2024-04-04T14:22:28Z",
                isArchived: false,
                isDraft: false,
                fieldData: {
                    name: "T-Shirt",
                    slug: "t-shirt",
                    description: "A plain cotton t-shirt.",
                    shippable: true,
                    "sku-properties": [
                        {
                            id: "Color",
                            name: "Color",
                            enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                        },
                    ],
                    category: ["category"],
                    "tax-category": "standard-taxable",
                    "default-sku": "default-sku",
                    "ec-product-type": "ff42fee0113744f693a764e3431a9cc2",
                },
            },
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: "2023-03-17T18:47:35Z",
                    lastUpdated: "2023-03-17T18:47:35Z",
                    createdOn: "2023-03-17T18:47:35Z",
                    fieldData: {
                        "sku-values": { color: "blue", size: "small" },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: { value: 2499, unit: "USD", currency: "USD" },
                        "main-image": "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        "sku-properties": [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                            },
                        ],
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/sites/580e63e98c9a982ac9b8b741/products/580e63fc8c9a982ac9b8b745")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.get("580e63e98c9a982ac9b8b741", "580e63fc8c9a982ac9b8b745");
        expect(response).toEqual({
            product: {
                id: "660eb7a486d1d6e0412292d7",
                cmsLocaleId: "653ad57de882f528b32e810e",
                lastPublished: new Date("2024-04-04T14:24:19.000Z"),
                lastUpdated: new Date("2024-04-04T14:30:19.000Z"),
                createdOn: new Date("2024-04-04T14:22:28.000Z"),
                isArchived: false,
                isDraft: false,
                fieldData: {
                    name: "T-Shirt",
                    slug: "t-shirt",
                    description: "A plain cotton t-shirt.",
                    shippable: true,
                    skuProperties: [
                        {
                            id: "Color",
                            name: "Color",
                            enum: [
                                {
                                    id: "royal-blue",
                                    name: "Royal Blue",
                                    slug: "royal-blue",
                                },
                            ],
                        },
                    ],
                    category: ["category"],
                    taxCategory: "standard-taxable",
                    defaultSku: "default-sku",
                    ecProductType: "ff42fee0113744f693a764e3431a9cc2",
                },
            },
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                    lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                    createdOn: new Date("2023-03-17T18:47:35.000Z"),
                    fieldData: {
                        skuValues: {
                            color: "blue",
                            size: "small",
                        },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: {
                            value: 2499,
                            unit: "USD",
                            currency: "USD",
                        },
                        mainImage: "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        skuProperties: [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [
                                    {
                                        id: "royal-blue",
                                        name: "Royal Blue",
                                        slug: "royal-blue",
                                    },
                                ],
                            },
                        ],
                    },
                },
            ],
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/sites/site_id/products/product_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.get("site_id", "product_id");
        }).rejects.toThrow(Webflow.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "660eb7a486d1d6e0412292d7",
            cmsLocaleId: "653ad57de882f528b32e810e",
            lastPublished: "2024-04-04T14:24:19Z",
            lastUpdated: "2024-04-04T14:30:19Z",
            createdOn: "2024-04-04T14:22:28Z",
            isArchived: false,
            isDraft: false,
            fieldData: {
                name: "T-Shirt",
                slug: "t-shirt",
                description: "A plain cotton t-shirt.",
                shippable: true,
                "sku-properties": [
                    {
                        id: "Color",
                        name: "Color",
                        enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                    },
                ],
                category: ["category"],
                "tax-category": "standard-taxable",
                "default-sku": "default-sku",
                "ec-product-type": "ff42fee0113744f693a764e3431a9cc2",
            },
        };
        server
            .mockEndpoint()
            .patch("/sites/580e63e98c9a982ac9b8b741/products/580e63fc8c9a982ac9b8b745")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.update("580e63e98c9a982ac9b8b741", "580e63fc8c9a982ac9b8b745");
        expect(response).toEqual({
            id: "660eb7a486d1d6e0412292d7",
            cmsLocaleId: "653ad57de882f528b32e810e",
            lastPublished: new Date("2024-04-04T14:24:19.000Z"),
            lastUpdated: new Date("2024-04-04T14:30:19.000Z"),
            createdOn: new Date("2024-04-04T14:22:28.000Z"),
            isArchived: false,
            isDraft: false,
            fieldData: {
                name: "T-Shirt",
                slug: "t-shirt",
                description: "A plain cotton t-shirt.",
                shippable: true,
                skuProperties: [
                    {
                        id: "Color",
                        name: "Color",
                        enum: [
                            {
                                id: "royal-blue",
                                name: "Royal Blue",
                                slug: "royal-blue",
                            },
                        ],
                    },
                ],
                category: ["category"],
                taxCategory: "standard-taxable",
                defaultSku: "default-sku",
                ecProductType: "ff42fee0113744f693a764e3431a9cc2",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.update("site_id", "product_id");
        }).rejects.toThrow(Webflow.InternalServerError);
    });

    test("create-sku (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: "2023-03-17T18:47:35Z",
                    lastUpdated: "2023-03-17T18:47:35Z",
                    createdOn: "2023-03-17T18:47:35Z",
                    fieldData: {
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: { value: 2499, unit: "USD", currency: "USD" },
                    },
                },
            ],
        };
        const rawResponseBody = {
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: "2023-03-17T18:47:35Z",
                    lastUpdated: "2023-03-17T18:47:35Z",
                    createdOn: "2023-03-17T18:47:35Z",
                    fieldData: {
                        "sku-values": { color: "blue", size: "small" },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: { value: 2499, unit: "USD", currency: "USD" },
                        "main-image": "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        "sku-properties": [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                            },
                        ],
                    },
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/sites/580e63e98c9a982ac9b8b741/products/580e63fc8c9a982ac9b8b745/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.createSku("580e63e98c9a982ac9b8b741", "580e63fc8c9a982ac9b8b745", {
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                    lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                    createdOn: new Date("2023-03-17T18:47:35.000Z"),
                    fieldData: {
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: {
                            value: 2499,
                            unit: "USD",
                            currency: "USD",
                        },
                    },
                },
            ],
        });
        expect(response).toEqual({
            skus: [
                {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                    lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                    createdOn: new Date("2023-03-17T18:47:35.000Z"),
                    fieldData: {
                        skuValues: {
                            color: "blue",
                            size: "small",
                        },
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: {
                            value: 2499,
                            unit: "USD",
                            currency: "USD",
                        },
                        mainImage: "https://www.example.com/image.jpg",
                        sku: "1234567890",
                        skuProperties: [
                            {
                                id: "Color",
                                name: "Color",
                                enum: [
                                    {
                                        id: "royal-blue",
                                        name: "Royal Blue",
                                        slug: "royal-blue",
                                    },
                                ],
                            },
                        ],
                    },
                },
            ],
        });
    });

    test("create-sku (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("create-sku (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("create-sku (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("create-sku (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("create-sku (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("create-sku (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("create-sku (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { skus: [{}, {}] };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sites/site_id/products/product_id/skus")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.createSku("site_id", "product_id", {
                skus: [{}, {}],
            });
        }).rejects.toThrow(Webflow.InternalServerError);
    });

    test("update-sku (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {
            sku: {
                id: "66072fb71b89448912e2681c",
                cmsLocaleId: "653ad57de882f528b32e810e",
                lastPublished: "2023-03-17T18:47:35Z",
                lastUpdated: "2023-03-17T18:47:35Z",
                createdOn: "2023-03-17T18:47:35Z",
                fieldData: {
                    name: "Colorful T-shirt - Default",
                    slug: "colorful-t-shirt-default",
                    price: { value: 2499, unit: "USD", currency: "USD" },
                },
            },
        };
        const rawResponseBody = {
            id: "66072fb71b89448912e2681c",
            cmsLocaleId: "653ad57de882f528b32e810e",
            lastPublished: "2023-03-17T18:47:35Z",
            lastUpdated: "2023-03-17T18:47:35Z",
            createdOn: "2023-03-17T18:47:35Z",
            fieldData: {
                "sku-values": { color: "blue", size: "small" },
                name: "Colorful T-shirt - Default",
                slug: "colorful-t-shirt-default",
                price: { value: 2499, unit: "USD", currency: "USD" },
                "compare-at-price": { value: 100, unit: "USD" },
                "ec-sku-billing-method": "one-time",
                "ec-sku-subscription-plan": { interval: "day", frequency: 1, trial: 7, plans: [{}] },
                "main-image": "https://www.example.com/image.jpg",
                sku: "1234567890",
                "sku-properties": [
                    {
                        id: "Color",
                        name: "Color",
                        enum: [{ id: "royal-blue", name: "Royal Blue", slug: "royal-blue" }],
                    },
                ],
            },
        };
        server
            .mockEndpoint()
            .patch("/sites/580e63e98c9a982ac9b8b741/products/580e63fc8c9a982ac9b8b745/skus/5e8518516e147040726cc415")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.products.updateSku(
            "580e63e98c9a982ac9b8b741",
            "580e63fc8c9a982ac9b8b745",
            "5e8518516e147040726cc415",
            {
                sku: {
                    id: "66072fb71b89448912e2681c",
                    cmsLocaleId: "653ad57de882f528b32e810e",
                    lastPublished: new Date("2023-03-17T18:47:35.000Z"),
                    lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
                    createdOn: new Date("2023-03-17T18:47:35.000Z"),
                    fieldData: {
                        name: "Colorful T-shirt - Default",
                        slug: "colorful-t-shirt-default",
                        price: {
                            value: 2499,
                            unit: "USD",
                            currency: "USD",
                        },
                    },
                },
            },
        );
        expect(response).toEqual({
            id: "66072fb71b89448912e2681c",
            cmsLocaleId: "653ad57de882f528b32e810e",
            lastPublished: new Date("2023-03-17T18:47:35.000Z"),
            lastUpdated: new Date("2023-03-17T18:47:35.000Z"),
            createdOn: new Date("2023-03-17T18:47:35.000Z"),
            fieldData: {
                skuValues: {
                    color: "blue",
                    size: "small",
                },
                name: "Colorful T-shirt - Default",
                slug: "colorful-t-shirt-default",
                price: {
                    value: 2499,
                    unit: "USD",
                    currency: "USD",
                },
                compareAtPrice: {
                    value: 100,
                    unit: "USD",
                },
                ecSkuBillingMethod: "one-time",
                ecSkuSubscriptionPlan: {
                    interval: "day",
                    frequency: 1,
                    trial: 7,
                    plans: [{}],
                },
                mainImage: "https://www.example.com/image.jpg",
                sku: "1234567890",
                skuProperties: [
                    {
                        id: "Color",
                        name: "Color",
                        enum: [
                            {
                                id: "royal-blue",
                                name: "Royal Blue",
                                slug: "royal-blue",
                            },
                        ],
                    },
                ],
            },
        });
    });

    test("update-sku (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.BadRequestError);
    });

    test("update-sku (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.UnauthorizedError);
    });

    test("update-sku (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.ForbiddenError);
    });

    test("update-sku (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.NotFoundError);
    });

    test("update-sku (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.ConflictError);
    });

    test("update-sku (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.TooManyRequestsError);
    });

    test("update-sku (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = { sku: {} };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .patch("/sites/site_id/products/product_id/skus/sku_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.products.updateSku("site_id", "product_id", "sku_id", {
                sku: {},
            });
        }).rejects.toThrow(Webflow.InternalServerError);
    });
});
