/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";

export const UsersUpdateResponseDataData: core.serialization.ObjectSchema<
    serializers.UsersUpdateResponseDataData.Raw,
    Webflow.UsersUpdateResponseDataData
> = core.serialization.object({
    name: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
    acceptPrivacy: core.serialization.property("accept-privacy", core.serialization.boolean().optional()),
    acceptCommunications: core.serialization.property("accept-communications", core.serialization.boolean().optional()),
    additionalProperties: core.serialization.string().optional(),
});

export declare namespace UsersUpdateResponseDataData {
    interface Raw {
        name?: string | null;
        email?: string | null;
        "accept-privacy"?: boolean | null;
        "accept-communications"?: boolean | null;
        additionalProperties?: string | null;
    }
}
