// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";
import { UserAccountAddedPayloadPayload } from "./UserAccountAddedPayloadPayload";

export const UserAccountAddedPayload: core.serialization.ObjectSchema<
    serializers.UserAccountAddedPayload.Raw,
    Webflow.UserAccountAddedPayload
> = core.serialization.object({
    triggerType: core.serialization.stringLiteral("user_account_added").optional(),
    payload: UserAccountAddedPayloadPayload.optional(),
});

export declare namespace UserAccountAddedPayload {
    export interface Raw {
        triggerType?: "user_account_added" | null;
        payload?: UserAccountAddedPayloadPayload.Raw | null;
    }
}
