/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { UsersUpdateResponseStatus } from "./UsersUpdateResponseStatus";
import { UsersUpdateResponseAccessGroupsItem } from "./UsersUpdateResponseAccessGroupsItem";
import { UsersUpdateResponseData } from "./UsersUpdateResponseData";

export const UsersUpdateResponse: core.serialization.ObjectSchema<
    serializers.UsersUpdateResponse.Raw,
    Webflow.UsersUpdateResponse
> = core.serialization.object({
    id: core.serialization.string().optional(),
    isEmailVerified: core.serialization.boolean().optional(),
    lastUpdated: core.serialization.date().optional(),
    invitedOn: core.serialization.date().optional(),
    createdOn: core.serialization.date().optional(),
    lastLogin: core.serialization.date().optional(),
    status: UsersUpdateResponseStatus.optional(),
    accessGroups: core.serialization.list(UsersUpdateResponseAccessGroupsItem).optional(),
    data: UsersUpdateResponseData.optional(),
});

export declare namespace UsersUpdateResponse {
    interface Raw {
        id?: string | null;
        isEmailVerified?: boolean | null;
        lastUpdated?: string | null;
        invitedOn?: string | null;
        createdOn?: string | null;
        lastLogin?: string | null;
        status?: UsersUpdateResponseStatus.Raw | null;
        accessGroups?: UsersUpdateResponseAccessGroupsItem.Raw[] | null;
        data?: UsersUpdateResponseData.Raw | null;
    }
}
