// This file was auto-generated by Fern from our API Definition.

import type * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import type * as serializers from "../../../index";

export const UsersListRequestSort: core.serialization.Schema<
    serializers.UsersListRequestSort.Raw,
    Webflow.UsersListRequestSort
> = core.serialization.enum_([
    "CreatedOn",
    "-CreatedOn",
    "Email",
    "-Email",
    "Status",
    "-Status",
    "LastLogin",
    "-LastLogin",
    "UpdatedOn",
    "-UpdatedOn",
]);

export declare namespace UsersListRequestSort {
    export type Raw =
        | "CreatedOn"
        | "-CreatedOn"
        | "Email"
        | "-Email"
        | "Status"
        | "-Status"
        | "LastLogin"
        | "-LastLogin"
        | "UpdatedOn"
        | "-UpdatedOn";
}
