/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Webflow from "../../../../api/index";
import * as core from "../../../../core";
import { UsersListResponseUsersItemAccessGroupsItemType } from "./UsersListResponseUsersItemAccessGroupsItemType";

export const UsersListResponseUsersItemAccessGroupsItem: core.serialization.ObjectSchema<
    serializers.UsersListResponseUsersItemAccessGroupsItem.Raw,
    Webflow.UsersListResponseUsersItemAccessGroupsItem
> = core.serialization.object({
    slug: core.serialization.string().optional(),
    type: UsersListResponseUsersItemAccessGroupsItemType.optional(),
});

export declare namespace UsersListResponseUsersItemAccessGroupsItem {
    interface Raw {
        slug?: string | null;
        type?: UsersListResponseUsersItemAccessGroupsItemType.Raw | null;
    }
}
