/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Webflow from "../../../../../api";
import * as core from "../../../../../core";

export const ProductsCreateRequest: core.serialization.Schema<
    serializers.ProductsCreateRequest.Raw,
    Webflow.ProductsCreateRequest
> = core.serialization.object({
    publishStatus: core.serialization.lazy(async () => (await import("../../../..")).PublishStatus).optional(),
    product: core.serialization.lazyObject(async () => (await import("../../../..")).Product),
    sku: core.serialization.lazyObject(async () => (await import("../../../..")).Sku),
});

export declare namespace ProductsCreateRequest {
    interface Raw {
        publishStatus?: serializers.PublishStatus.Raw | null;
        product: serializers.Product.Raw;
        sku: serializers.Sku.Raw;
    }
}
