/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Webflow from "../../../../../api";
import * as core from "../../../../../core";

export const ProductSkuUpdate: core.serialization.Schema<serializers.ProductSkuUpdate.Raw, Webflow.ProductSkuUpdate> =
    core.serialization.object({
        publishStatus: core.serialization.lazy(async () => (await import("../../../..")).PublishStatus).optional(),
        product: core.serialization.lazyObject(async () => (await import("../../../..")).Product).optional(),
        sku: core.serialization.lazyObject(async () => (await import("../../../..")).Sku).optional(),
    });

export declare namespace ProductSkuUpdate {
    interface Raw {
        publishStatus?: serializers.PublishStatus.Raw | null;
        product?: serializers.Product.Raw | null;
        sku?: serializers.Sku.Raw | null;
    }
}
