/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Webflow from "../../../../../api/index";
import * as core from "../../../../../core";
import { PublishStatus } from "../../../../types/PublishStatus";
import { Product } from "../../../../types/Product";
import { Sku } from "../../../../types/Sku";

export const ProductSkuCreate: core.serialization.Schema<serializers.ProductSkuCreate.Raw, Webflow.ProductSkuCreate> =
    core.serialization.object({
        publishStatus: PublishStatus.optional(),
        product: Product.optional(),
        sku: Sku.optional(),
    });

export declare namespace ProductSkuCreate {
    interface Raw {
        publishStatus?: PublishStatus.Raw | null;
        product?: Product.Raw | null;
        sku?: Sku.Raw | null;
    }
}
