/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SitesUpdateRequest {
    /** The name of the site */
    name?: string;
    /** The parent folder ID of the site */
    parentFolderId?: string;
}
