/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool.js";
import { WebflowClient } from "../../../src/Client";

describe("WellKnown", () => {
    test("put", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {
            fileName: "apple-app-site-association.txt",
            fileData:
                '{\n  "applinks": {\n    "apps": [],\n    "details": [\n  {\n    "appID": "ABCDE12345.com.example.app",\n    "paths": [ "/*", "/some/path/*" ]\n      }\n    ]\n  }\n}\n',
            contentType: "application/json",
        };

        server
            .mockEndpoint()
            .put("/sites/580e63e98c9a982ac9b8b741/well_known")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.sites.wellKnown.put("580e63e98c9a982ac9b8b741", {
            fileName: "apple-app-site-association.txt",
            fileData:
                '{\n  "applinks": {\n    "apps": [],\n    "details": [\n  {\n    "appID": "ABCDE12345.com.example.app",\n    "paths": [ "/*", "/some/path/*" ]\n      }\n    ]\n  }\n}\n',
            contentType: "application/json",
        });
        expect(response).toEqual(undefined);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new WebflowClient({
            accessToken: "test",
            environment: { base: server.baseUrl, dataApi: server.baseUrl, contentDeliveryApi: server.baseUrl },
        });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .delete("/sites/580e63e98c9a982ac9b8b741/well_known")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.sites.wellKnown.delete("580e63e98c9a982ac9b8b741");
        expect(response).toEqual(undefined);
    });
});
