/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Open Graph fields for the Page
 */
export interface UpdatePageSettingsRequestOpenGraph {
    /** The title supplied to Open Graph annotations */
    title?: string;
    /** The description supplied to Open Graph annotations */
    description?: string;
}
